APP         = webview
TITLE       = Web view
VERSION     = 1.0
TYPE        = gui
DESCRIPTION = A small browser made with the SDK web view (bweb_*), and a page that talks to its app
AUTHOR      = Banana OS SDK
CATEGORY    = Internet
SRCS        = webview.c

include ../../banana.mk
