APP         = mandel
TITLE       = Mandelbrot
VERSION     = 1.0
TYPE        = gui
DESCRIPTION = The Mandelbrot set - click to zoom in, right-click to zoom out
AUTHOR      = Banana OS SDK
CATEGORY    = Graphics
SRCS        = mandel.c

include ../../banana.mk
