APP         = clock
TITLE       = Clock
VERSION     = 1.0
TYPE        = gui
DESCRIPTION = An analog and digital clock
AUTHOR      = Banana OS SDK
CATEGORY    = Utilities
SRCS        = clock.c

include ../../banana.mk
