APP         = guess
TITLE       = Guess the Number
VERSION     = 1.0
TYPE        = console
DESCRIPTION = Guess a number between 1 and 100 in as few tries as possible
AUTHOR      = Banana OS SDK
SRCS        = guess.c

include ../../banana.mk
