APP         = hello
TITLE       = Hello World
VERSION     = 1.0
TYPE        = console
DESCRIPTION = The smallest Banana OS app: prints a greeting and some system facts
AUTHOR      = Banana OS SDK
SRCS        = hello.c

include ../../banana.mk
