APP         = photos
TITLE       = Photos
VERSION     = 1.0
TYPE        = gui
DESCRIPTION = Your pictures: PNG, JPEG, BMP, GIF - browse a folder, zoom, rotate, set as wallpaper
AUTHOR      = Banana OS
SRCS        = photos.c

LIBS_i686   = $(shell gcc -m32 -print-libgcc-file-name)
LIBS_x86_64 = $(shell gcc -m64 -print-libgcc-file-name)

include ../../sdk/banana.mk
