DRIVER      = edu
TITLE       = QEMU edu device
VERSION     = 1.0
DESCRIPTION = Driver Kit example: the QEMU edu teaching device (qemu -device edu)
AUTHOR      = Banana OS Driver Kit
SRCS        = edu.c

include ../../driver.mk
