APP         = tones
TITLE       = Tones
VERSION     = 1.0
TYPE        = console
DESCRIPTION = Plays a little tune through the sound card (or the PC speaker)
AUTHOR      = Banana OS SDK
CATEGORY    = Sound & Music
SRCS        = tones.c

include ../../banana.mk
