APP         = threads
TITLE       = Threads
VERSION     = 1.0
TYPE        = console
DESCRIPTION = Counts primes with several threads sharing a total under a mutex
AUTHOR      = Banana OS SDK
SRCS        = threads.c

include ../../banana.mk
