APP         = paint
TITLE       = Paint
VERSION     = 1.0
TYPE        = gui
DESCRIPTION = Draw with the mouse; save your picture to ~/Pictures
AUTHOR      = Banana OS SDK
SRCS        = paint.c

include ../../banana.mk
