DRIVER      = bochsfb
TITLE       = Bochs display (example)
VERSION     = 1.0
DESCRIPTION = Driver Kit example: a display driver for the Bochs / QEMU standard VGA
AUTHOR      = Banana OS Driver Kit
SRCS        = bochsfb.c

include ../../driver.mk
