/* /var/www/demo.php, created by httpd next to the default index page
 * (generated from web/test/cases/demo.php by web/test/embed.py) */
#include "httpd_demo.h"

const char HTTPD_DEMO_PHP[] =
    "<?php\n"
    "$name = isset($_GET['name']) ? trim($_GET['name']) : '';\n"
    "$fruits = ['banana' => 105, 'apple' => 95, 'cherry' => 50, 'mango' => 200];\n"
    "arsort($fruits);\n"
    "\n"
    "function greeting($who) {\n"
    "    $h = (int)date('G');\n"
    "    $part = $h < 12 ? 'Good morning' : ($h < 18 ? 'Good afternoon' : 'Good evening');\n"
    "    return $who === '' ? \"$part!\" : \"$part, \" . htmlspecialchars($who) . \"!\";\n"
    "}\n"
    "\n"
    "$book = 'guestbook.txt';\n"
    "if (isset($_GET['msg']) && trim($_GET['msg']) !== '' && function_exists('file_put_contents')) {\n"
    "    $line = date('H:i') . ' ' . str_replace(\"\\n\", ' ', trim($_GET['msg'])) . \"\\n\";\n"
    "    file_put_contents($book, $line, FILE_APPEND);\n"
    "}\n"
    "?>\n"
    "<!DOCTYPE html>\n"
    "<html>\n"
    "<head>\n"
    "<title>PHP on Banana OS</title>\n"
    "<style>\n"
    "  body { background: #f7f3e3; margin: 0; }\n"
    "  .top { background: #6c5ce7; color: #fff; padding: 10px 18px; }\n"
    "  .top h1 { margin: 0; font-size: 26px; }\n"
    "  .box { background: #fff; border: 1px solid #d8cfa8; margin: 10px 18px; padding: 8px 12px; }\n"
    "  h2 { font-size: 16px; color: #4b3fb0; margin: 2px 0 6px 0; }\n"
    "  table { border-collapse: collapse; }\n"
    "  td, th { border: 1px solid #ccc; padding: 2px 8px; }\n"
    "  th { background: #efeafc; }\n"
    "  .big { color: #c0392b; font-weight: bold; }\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div class=\"top\"><h1>PHP <?= PHP_VERSION ?> on Banana OS</h1>\n"
    "Served by <?= $_SERVER['SERVER_SOFTWARE'] ?> at <?= date('Y-m-d H:i:s') ?></div>\n"
    "\n"
    "<div class=\"box\">\n"
    "  <h2><?= greeting($name) ?></h2>\n"
    "  <form action=\"demo.php\">\n"
    "    Your name: <input name=\"name\" value=\"<?= htmlspecialchars($name) ?>\">\n"
    "    <input type=\"submit\" value=\"Say hello\">\n"
    "  </form>\n"
    "</div>\n"
    "\n"
    "<div class=\"box\">\n"
    "  <h2>Calories (sorted with arsort)</h2>\n"
    "  <table>\n"
    "    <tr><th>#</th><th>Fruit</th><th>kcal</th></tr>\n"
    "<?php $i = 1; foreach ($fruits as $fruit => $kcal): ?>\n"
    "    <tr><td><?= $i++ ?></td><td><?= ucfirst($fruit) ?></td>\n"
    "        <td<?php if ($kcal > 100) echo ' class=\"big\"'; ?>><?= $kcal ?></td></tr>\n"
    "<?php endforeach; ?>\n"
    "  </table>\n"
    "  <p>Total: <?= array_sum($fruits) ?> kcal, average <?= number_format(array_sum($fruits) / count($fruits), 1) ?>.</p>\n"
    "</div>\n"
    "\n"
    "<div class=\"box\">\n"
    "  <h2>Loops and math</h2>\n"
    "  <p>Squares: <?php for ($n = 1; $n <= 10; $n++) { echo $n * $n, $n < 10 ? ', ' : ''; } ?></p>\n"
    "  <p>2<sup>16</sup> = <?= pow(2, 16) ?>, sqrt(2) = <?= round(sqrt(2), 6) ?>, md5(\"banana\") = <?= md5(\"banana\") ?></p>\n"
    "</div>\n"
    "\n"
    "<div class=\"box\">\n"
    "  <h2>Guestbook</h2>\n"
    "  <form action=\"demo.php\">\n"
    "    <input name=\"msg\" placeholder=\"Leave a message\"> <input type=\"submit\" value=\"Sign\">\n"
    "  </form>\n"
    "  <ul>\n"
    "<?php\n"
    "$lines = function_exists('file') && file_exists($book) ? file($book) : [];\n"
    "if (count($lines) == 0) echo \"    <li><i>No messages yet.</i></li>\\n\";\n"
    "foreach (array_reverse($lines) as $l) echo \"    <li>\" . htmlspecialchars(trim($l)) . \"</li>\\n\";\n"
    "?>\n"
    "  </ul>\n"
    "</div>\n"
    "\n"
    "<div class=\"box\">\n"
    "  <h2>JavaScript in a PHP page</h2>\n"
    "  <button onclick=\"this.textContent = 'Clicked at ' + new Date().toLocaleTimeString()\">Click me</button>\n"
    "</div>\n"
    "</body>\n"
    "</html>\n"
    ;

const unsigned int HTTPD_DEMO_PHP_LEN = sizeof(HTTPD_DEMO_PHP) - 1;
