/* generated from web/prelude.js by web/test/embed.pl: do not edit */
static const char k_prelude[] =
    "/* Run in every page before its own scripts: the web APIs that are easier to\n"
    " * write in script than in C.  web/prelude.h is generated from this file by\n"
    " * web/test/embed.pl. */\n"
    "(function(){\n"
    "var W = window, P = performance, marks = [];\n"
    "P.mark = function(n){ var e = {name:n, entryType:'mark', startTime:P.now(), duration:0}; marks.push(e); return e; };\n"
    "P.measure = function(n){ var e = {name:n, entryType:'measure', startTime:0, duration:P.now()}; marks.push(e); return e; };\n"
    "P.getEntriesByName = function(n){ return marks.filter(function(e){ return e.name === n; }); };\n"
    "P.getEntriesByType = function(t){ return marks.filter(function(e){ return e.entryType === t; }); };\n"
    "P.getEntries = function(){ return marks.slice(); };\n"
    "P.clearMarks = P.clearMeasures = function(){ marks = []; };\n"
    "P.timeOrigin = 0; P.timing = {navigationStart:0}; P.navigation = {type:0};\n"
    "function enc(s){ return encodeURIComponent(s).replace(/%20/g, '+'); }\n"
    "function dec(s){ try { return decodeURIComponent(s.replace(/\\+/g, ' ')); } catch (e) { return s; } }\n"
    "class URLSearchParams {\n"
    "  constructor(init){ this._l = []; if (init == null) return;\n"
    "    if (typeof init === 'object') {\n"
    "      if (Array.isArray(init)) { for (var p of init) this._l.push([String(p[0]), String(p[1])]); }\n"
    "      else if (init._l) { this._l = init._l.map(function(p){ return [p[0], p[1]]; }); }\n"
    "      else { for (var k in init) this._l.push([k, String(init[k])]); }\n"
    "      return; }\n"
    "    var s = String(init); if (s[0] === '?') s = s.slice(1);\n"
    "    for (var part of s.split('&')) { if (!part) continue; var i = part.indexOf('=');\n"
    "      this._l.push(i < 0 ? [dec(part), ''] : [dec(part.slice(0, i)), dec(part.slice(i + 1))]); } }\n"
    "  get(k){ for (var p of this._l) if (p[0] === k) return p[1]; return null; }\n"
    "  getAll(k){ return this._l.filter(function(p){ return p[0] === k; }).map(function(p){ return p[1]; }); }\n"
    "  has(k){ return this.get(k) !== null; }\n"
    "  set(k, v){ var done = false; this._l = this._l.filter(function(p){ if (p[0] !== k) return true; if (done) return false; p[1] = String(v); done = true; return true; });\n"
    "    if (!done) this._l.push([k, String(v)]); if (this._u) this._u._sync(); }\n"
    "  append(k, v){ this._l.push([k, String(v)]); if (this._u) this._u._sync(); }\n"
    "  delete(k){ this._l = this._l.filter(function(p){ return p[0] !== k; }); if (this._u) this._u._sync(); }\n"
    "  forEach(f, t){ for (var p of this._l) f.call(t, p[1], p[0], this); }\n"
    "  keys(){ return this._l.map(function(p){ return p[0]; })[Symbol.iterator](); }\n"
    "  values(){ return this._l.map(function(p){ return p[1]; })[Symbol.iterator](); }\n"
    "  entries(){ return this._l.map(function(p){ return [p[0], p[1]]; })[Symbol.iterator](); }\n"
    "  [Symbol.iterator](){ return this.entries(); }\n"
    "  get size(){ return this._l.length; }\n"
    "  sort(){ this._l.sort(function(a, b){ return a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0; }); }\n"
    "  toString(){ return this._l.map(function(p){ return enc(p[0]) + '=' + enc(p[1]); }).join('&'); }\n"
    "}\n"
    "function resolve(u, base){\n"
    "  if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(u)) return u;\n"
    "  if (base == null) throw new TypeError('Invalid URL: ' + u);\n"
    "  var b = new URL(String(base));\n"
    "  if (u.slice(0, 2) === '//') return b.protocol + u;\n"
    "  if (u[0] === '/') return b.origin + u;\n"
    "  if (u[0] === '?') return b.origin + b.pathname + u;\n"
    "  if (u[0] === '#') return b.origin + b.pathname + b.search + u;\n"
    "  if (u === '') return b.origin + b.pathname + b.search;\n"
    "  var dir = b.pathname.slice(0, b.pathname.lastIndexOf('/') + 1), segs = (dir + u).split('/'), out = [];\n"
    "  for (var i = 0; i < segs.length; i++) { var s = segs[i];\n"
    "    if (s === '..') { if (out.length > 1) out.pop(); if (i === segs.length - 1) out.push(''); }\n"
    "    else if (s === '.') { if (i === segs.length - 1) out.push(''); }\n"
    "    else out.push(s); }\n"
    "  return b.origin + out.join('/');\n"
    "}\n"
    "var URL_RX = /^([a-zA-Z][a-zA-Z0-9+.-]*:)(?:\\/\\/(?:([^:@\\/]*)(?::([^@\\/]*))?@)?([^:\\/?#]*)(?::(\\d+))?)?([^?#]*)(\\?[^#]*)?(#.*)?$/;\n"
    "class URL {\n"
    "  constructor(u, base){ this._set(resolve(String(u), base)); }\n"
    "  _set(s){\n"
    "    var m = URL_RX.exec(s);\n"
    "    if (!m) throw new TypeError('Invalid URL: ' + s);\n"
    "    this.protocol = m[1].toLowerCase(); this.username = m[2] || ''; this.password = m[3] || '';\n"
    "    this.hostname = (m[4] || '').toLowerCase(); this.port = m[5] || '';\n"
    "    this.pathname = m[6] || (m[4] != null ? '/' : '');\n"
    "    this.search = m[7] && m[7] !== '?' ? m[7] : ''; this.hash = m[8] && m[8] !== '#' ? m[8] : '';\n"
    "    this.searchParams = new URLSearchParams(this.search); this.searchParams._u = this;\n"
    "  }\n"
    "  _sync(){ var q = this.searchParams.toString(); this.search = q ? '?' + q : ''; }\n"
    "  get host(){ return this.hostname + (this.port ? ':' + this.port : ''); }\n"
    "  get origin(){ return this.protocol + '//' + this.host; }\n"
    "  get href(){ return this.origin + this.pathname + this.search + this.hash; }\n"
    "  set href(v){ this._set(String(v)); }\n"
    "  toString(){ return this.href; }\n"
    "  toJSON(){ return this.href; }\n"
    "  static canParse(u, b){ try { new URL(u, b); return true; } catch (e) { return false; } }\n"
    "  static createObjectURL(){ return 'blob:null'; }\n"
    "  static revokeObjectURL(){}\n"
    "}\n"
    "W.URL = URL; W.URLSearchParams = URLSearchParams;\n"
    "\n"
    "/* event targets that are not elements (signals, ports, `class X extends EventTarget`) */\n"
    "class EventTarget {\n"
    "  addEventListener(t, f, o){ if (!f) return; var l = this.__ls || (this.__ls = {});\n"
    "    (l[t] || (l[t] = [])).push({f: f, once: !!(o && typeof o === 'object' && o.once)}); }\n"
    "  removeEventListener(t, f){ var l = this.__ls && this.__ls[t]; if (l) this.__ls[t] = l.filter(function(x){ return x.f !== f; }); }\n"
    "  dispatchEvent(ev){\n"
    "    try { if (!ev.target) ev.target = this; ev.currentTarget = this; } catch (e) {}\n"
    "    var h = this['on' + ev.type]; if (typeof h === 'function') h.call(this, ev);\n"
    "    var l = this.__ls && this.__ls[ev.type];\n"
    "    if (l) for (var x of l.slice()) {\n"
    "      if (x.once) this.removeEventListener(ev.type, x.f);\n"
    "      if (typeof x.f === 'function') x.f.call(this, ev); else if (x.f && x.f.handleEvent) x.f.handleEvent(ev);\n"
    "    }\n"
    "    return !ev.defaultPrevented;\n"
    "  }\n"
    "}\n"
    "class AbortSignal extends EventTarget {\n"
    "  constructor(){ super(); this.aborted = false; this.reason = undefined; this.onabort = null; }\n"
    "  throwIfAborted(){ if (this.aborted) throw this.reason; }\n"
    "  static abort(r){ var c = new AbortController(); c.abort(r); return c.signal; }\n"
    "  static timeout(ms){ var c = new AbortController(); setTimeout(function(){ c.abort(new Error('TimeoutError')); }, ms); return c.signal; }\n"
    "  static any(list){ var c = new AbortController();\n"
    "    for (var s of list) { if (s.aborted) { c.abort(s.reason); break; } s.addEventListener('abort', function(){ c.abort(this.reason); }); }\n"
    "    return c.signal; }\n"
    "}\n"
    "class AbortController {\n"
    "  constructor(){ this.signal = new AbortSignal(); }\n"
    "  abort(r){ var s = this.signal; if (s.aborted) return; s.aborted = true;\n"
    "    s.reason = r === undefined ? new Error('AbortError') : r; s.dispatchEvent({type: 'abort', target: s}); }\n"
    "}\n"
    "/* MessageChannel: messages arrive on the next turn (React's scheduler uses it) */\n"
    "class MessagePort extends EventTarget {\n"
    "  constructor(){ super(); this.onmessage = null; this._other = null; }\n"
    "  postMessage(d){ var o = this._other; setTimeout(function(){ o.dispatchEvent({type: 'message', data: d}); }, 0); }\n"
    "  start(){} close(){}\n"
    "}\n"
    "class MessageChannel {\n"
    "  constructor(){ this.port1 = new MessagePort(); this.port2 = new MessagePort(); this.port1._other = this.port2; this.port2._other = this.port1; }\n"
    "}\n"
    "W.EventTarget = EventTarget; W.AbortSignal = AbortSignal; W.AbortController = AbortController;\n"
    "W.MessagePort = MessagePort; W.MessageChannel = MessageChannel;\n"
    "var EP = Element.prototype;\n"
    "if (!EP.getRootNode) EP.getRootNode = function(){ var n = this; while (n.parentNode) n = n.parentNode; return n; };\n"
    "if (typeof crypto === 'undefined') W.crypto = {\n"
    "  getRandomValues: function(a){ for (var i = 0; i < a.length; i++) a[i] = Math.floor(Math.random() * 256); return a; },\n"
    "  randomUUID: function(){ return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c){\n"
    "    var r = Math.floor(Math.random() * 16); return (c === 'x' ? r : (r & 3) | 8).toString(16); }); },\n"
    "  subtle: {}\n"
    "};\n"
    "var D = document;\n"
    "if (!D.styleSheets) D.styleSheets = [];\n"
    "if (!D.adoptedStyleSheets) D.adoptedStyleSheets = [];\n"
    "if (!D.fonts) D.fonts = { ready: Promise.resolve(), status: 'loaded', check: function(){ return true; },\n"
    "  load: function(){ return Promise.resolve([]); }, add: function(){}, delete: function(){}, forEach: function(){},\n"
    "  addEventListener: function(){}, removeEventListener: function(){} };\n"
    "if (typeof CSSStyleSheet === 'undefined') W.CSSStyleSheet = class CSSStyleSheet {\n"
    "  constructor(){ this.cssRules = []; } replaceSync(t){ this.text = t; } replace(t){ this.text = t; return Promise.resolve(this); }\n"
    "  insertRule(r, i){ this.cssRules.splice(i || 0, 0, {cssText: r}); return i || 0; } deleteRule(i){ this.cssRules.splice(i, 1); }\n"
    "};\n"
    "if (typeof queueMicrotask !== 'function') W.queueMicrotask = function(f){ Promise.resolve().then(f); };\n"
    "if (!String.raw) String.raw = function(s){ var r = s.raw, out = ''; for (var i = 0; i < r.length; i++) { out += r[i]; if (i + 1 < arguments.length && i + 1 < r.length) out += arguments[i + 1]; } return out; };\n"
    "/* iterators over arrays and array-likes (for-of on arrays is native, but\n"
    " * code also calls a[Symbol.iterator]() / .values() / .entries() itself) */\n"
    "var mkIt = function(a, kind){ var i = 0; var it = { next: function(){\n"
    "    if (i >= a.length) return {value: undefined, done: true};\n"
    "    var k = i++; return {value: kind === 1 ? k : kind === 2 ? [k, a[k]] : a[k], done: false}; } };\n"
    "  it[Symbol.iterator] = function(){ return it; }; return it; };\n"
    "var AP = Array.prototype;\n"
    "if (!AP[Symbol.iterator]) AP[Symbol.iterator] = function(){ return mkIt(this, 0); };\n"
    "if (!AP.values) AP.values = function(){ return mkIt(this, 0); };\n"
    "if (!AP.keys) AP.keys = function(){ return mkIt(this, 1); };\n"
    "if (!AP.entries) AP.entries = function(){ return mkIt(this, 2); };\n"
    "/* typed arrays: the methods that take callbacks (the rest are native, script_typed.c) */\n"
    "var TP = W.__TypedArrayProto;\n"
    "if (TP) {\n"
    "  var mk = function(t, n){ return new t.constructor(n); };\n"
    "  TP.forEach = function(f, th){ for (var i = 0; i < this.length; i++) f.call(th, this[i], i, this); };\n"
    "  TP.map = function(f, th){ var r = mk(this, this.length); for (var i = 0; i < this.length; i++) r[i] = f.call(th, this[i], i, this); return r; };\n"
    "  TP.filter = function(f, th){ var a = []; for (var i = 0; i < this.length; i++) if (f.call(th, this[i], i, this)) a.push(this[i]); return new this.constructor(a); };\n"
    "  TP.reduce = function(f, acc){ var i = 0; if (arguments.length < 2) acc = this[i++]; for (; i < this.length; i++) acc = f(acc, this[i], i, this); return acc; };\n"
    "  TP.reduceRight = function(f, acc){ var i = this.length - 1; if (arguments.length < 2) acc = this[i--]; for (; i >= 0; i--) acc = f(acc, this[i], i, this); return acc; };\n"
    "  TP.every = function(f, th){ for (var i = 0; i < this.length; i++) if (!f.call(th, this[i], i, this)) return false; return true; };\n"
    "  TP.some = function(f, th){ for (var i = 0; i < this.length; i++) if (f.call(th, this[i], i, this)) return true; return false; };\n"
    "  TP.find = function(f, th){ for (var i = 0; i < this.length; i++) if (f.call(th, this[i], i, this)) return this[i]; };\n"
    "  TP.findIndex = function(f, th){ for (var i = 0; i < this.length; i++) if (f.call(th, this[i], i, this)) return i; return -1; };\n"
    "  TP.findLast = function(f, th){ for (var i = this.length - 1; i >= 0; i--) if (f.call(th, this[i], i, this)) return this[i]; };\n"
    "  TP.findLastIndex = function(f, th){ for (var i = this.length - 1; i >= 0; i--) if (f.call(th, this[i], i, this)) return i; return -1; };\n"
    "  TP.at = function(i){ i = Math.trunc(i) || 0; if (i < 0) i += this.length; return this[i]; };\n"
    "  TP.sort = function(f){ var a = []; for (var i = 0; i < this.length; i++) a.push(this[i]);\n"
    "    a.sort(f || function(x, y){ return x - y; }); for (var j = 0; j < a.length; j++) this[j] = a[j]; return this; };\n"
    "  TP.toString = function(){ return this.join(','); };\n"
    "  TP.toLocaleString = TP.toString;\n"
    "  TP.keys = function(){ return mkIt(this, 1); };\n"
    "  TP.values = function(){ return mkIt(this, 0); };\n"
    "  TP.entries = function(){ return mkIt(this, 2); };\n"
    "  TP[Symbol.iterator] = TP.values;\n"
    "}\n"
    "if (typeof TextEncoder === 'undefined') W.TextEncoder = class TextEncoder {\n"
    "  get encoding(){ return 'utf-8'; }\n"
    "  encode(s){ return __utf8_encode(s === undefined ? '' : String(s)); }\n"
    "  encodeInto(s, dst){ var b = __utf8_encode(String(s)), n = Math.min(b.length, dst.length); dst.set(b.subarray(0, n)); return {read: s.length, written: n}; }\n"
    "};\n"
    "if (typeof TextDecoder === 'undefined') W.TextDecoder = class TextDecoder {\n"
    "  constructor(l){ this.encoding = (l || 'utf-8').toLowerCase(); }\n"
    "  decode(b){ return b === undefined ? '' : __utf8_decode(b); }\n"
    "};\n"
    "if (typeof Reflect === 'undefined') W.Reflect = {\n"
    "  apply: function(f, t, a){ return f.apply(t, a || []); },\n"
    "  construct: function(C, a){ var A = a || []; switch (A.length) { case 0: return new C(); case 1: return new C(A[0]);\n"
    "    case 2: return new C(A[0], A[1]); case 3: return new C(A[0], A[1], A[2]); default: return new C(A[0], A[1], A[2], A[3]); } },\n"
    "  get: function(o, k){ return o[k]; },\n"
    "  set: function(o, k, v){ o[k] = v; return true; },\n"
    "  has: function(o, k){ return k in o; },\n"
    "  ownKeys: function(o){ return Object.getOwnPropertyNames(o); },\n"
    "  defineProperty: function(o, k, d){ try { Object.defineProperty(o, k, d); return true; } catch (e) { return false; } },\n"
    "  deleteProperty: function(o, k){ return delete o[k]; },\n"
    "  getPrototypeOf: function(o){ return Object.getPrototypeOf(o); },\n"
    "  setPrototypeOf: function(o, p){ Object.setPrototypeOf(o, p); return true; },\n"
    "  getOwnPropertyDescriptor: function(o, k){ return Object.getOwnPropertyDescriptor(o, k); },\n"
    "  isExtensible: function(){ return true; }, preventExtensions: function(){ return true; }\n"
    "};\n"
    "if (typeof escape !== 'function') {\n"
    "  W.escape = function(s){ s = String(s); var r = ''; for (var i = 0; i < s.length; i++) { var c = s.charCodeAt(i), ch = s.charAt(i);\n"
    "    if (/[A-Za-z0-9@*_+\\-.\\/]/.test(ch)) r += ch; else r += '%' + (c < 16 ? '0' : '') + c.toString(16).toUpperCase(); } return r; };\n"
    "  W.unescape = function(s){ return String(s).replace(/%([0-9A-Fa-f]{2})/g, function(m, h){ return String.fromCharCode(parseInt(h, 16)); }); };\n"
    "}\n"
    "var M = Math;\n"
    "if (!M.log1p) M.log1p = function(x){ return M.log(1 + x); };\n"
    "if (!M.expm1) M.expm1 = function(x){ return M.exp(x) - 1; };\n"
    "if (!M.sinh) M.sinh = function(x){ return (M.exp(x) - M.exp(-x)) / 2; };\n"
    "if (!M.cosh) M.cosh = function(x){ return (M.exp(x) + M.exp(-x)) / 2; };\n"
    "if (!M.tanh) M.tanh = function(x){ if (x > 20) return 1; if (x < -20) return -1; var a = M.exp(2 * x); return (a - 1) / (a + 1); };\n"
    "var O = Object, OP = Object.prototype;\n"
    "if (!O.isExtensible) O.isExtensible = function(){ return true; };\n"
    "if (!O.getOwnPropertySymbols) O.getOwnPropertySymbols = function(){ return []; };\n"
    "if (!O.getOwnPropertyDescriptors) O.getOwnPropertyDescriptors = function(o){ var r = {}; O.getOwnPropertyNames(o).forEach(function(k){ r[k] = O.getOwnPropertyDescriptor(o, k); }); return r; };\n"
    "if (!OP.isPrototypeOf) OP.isPrototypeOf = function(o){ while (o != null) { o = O.getPrototypeOf(o); if (o === this) return true; } return false; };\n"
    "if (!OP.propertyIsEnumerable) OP.propertyIsEnumerable = function(k){ return O.prototype.hasOwnProperty.call(this, k); };\n"
    "if (!OP.valueOf) OP.valueOf = function(){ return this; };\n"
    "if (!OP.toLocaleString) OP.toLocaleString = function(){ return this.toString(); };\n"
    "var NP = Number.prototype;\n"
    "if (!NP.toPrecision) NP.toPrecision = function(p){ if (p === undefined) return String(this); var x = Number(this);\n"
    "  if (x === 0) return x.toFixed(p - 1); var e = Math.floor(Math.log10(Math.abs(x))); return (e < -6 || e >= p) ? x.toExponential(p - 1) : x.toFixed(Math.max(0, p - 1 - e)); };\n"
    "if (!NP.toExponential) NP.toExponential = function(d){ var x = Number(this); if (x === 0) return (d ? (0).toFixed(d) : '0') + 'e+0';\n"
    "  var e = Math.floor(Math.log10(Math.abs(x))), m = x / Math.pow(10, e); if (d === undefined) d = Math.max(0, String(m).replace('-', '').length - 2);\n"
    "  var ms = m.toFixed(d); if (Math.abs(parseFloat(ms)) >= 10) { e++; ms = (m / 10).toFixed(d); } return ms + 'e' + (e < 0 ? '-' : '+') + Math.abs(e); };\n"
    "if (!NP.toLocaleString) NP.toLocaleString = function(){ var p = String(this).split('.'); p[0] = p[0].replace(/\\B(?=(\\d{3})+(?!\\d))/g, ','); return p.join('.'); };\n"
    "var SP = String.prototype;\n"
    "if (!SP.toLocaleLowerCase) SP.toLocaleLowerCase = SP.toLowerCase;\n"
    "if (!SP.toLocaleUpperCase) SP.toLocaleUpperCase = SP.toUpperCase;\n"
    "if (!Array.prototype.copyWithin) Array.prototype.copyWithin = function(t, s, e){ var n = this.length, c = this.slice(s, e === undefined ? n : e);\n"
    "  for (var i = 0; i < c.length && t + i < n; i++) this[t + i] = c[i]; return this; };\n"
    "if (!Function.prototype.toString) Function.prototype.toString = function(){ return 'function ' + (this.name || '') + '() { [native code] }'; };\n"
    "if (typeof WeakRef === 'undefined') W.WeakRef = class WeakRef { constructor(t){ this._t = t; } deref(){ return this._t; } };\n"
    "if (typeof Headers === 'undefined') W.Headers = class Headers {\n"
    "  constructor(i){ this._h = {}; if (i) { if (i._h) i = i._h; for (var k in i) this._h[k.toLowerCase()] = String(i[k]); } }\n"
    "  get(k){ var v = this._h[String(k).toLowerCase()]; return v === undefined ? null : v; }\n"
    "  set(k, v){ this._h[String(k).toLowerCase()] = String(v); } append(k, v){ var o = this.get(k); this.set(k, o === null ? v : o + ', ' + v); }\n"
    "  has(k){ return this.get(k) !== null; } delete(k){ delete this._h[String(k).toLowerCase()]; }\n"
    "  forEach(f, t){ for (var k in this._h) f.call(t, this._h[k], k, this); }\n"
    "  entries(){ var a = []; for (var k in this._h) a.push([k, this._h[k]]); return a[Symbol.iterator](); }\n"
    "  [Symbol.iterator](){ return this.entries(); }\n"
    "};\n"
    "W.FormData = class FormData {\n"
    "  constructor(form){ this._l = [];\n"
    "    if (form && form.querySelectorAll) { var els = form.querySelectorAll('input,select,textarea');\n"
    "      for (var i = 0; i < els.length; i++) { var e = els[i], n = e.getAttribute('name'); if (!n || e.hasAttribute('disabled')) continue;\n"
    "        var t = (e.getAttribute('type') || '').toLowerCase();\n"
    "        if (t === 'submit' || t === 'button' || t === 'reset' || t === 'image') continue;\n"
    "        if ((t === 'checkbox' || t === 'radio') && !e.checked) continue;\n"
    "        if (t === 'file') { var fl = e.files; if (fl && fl.length) for (var k = 0; k < fl.length; k++) this.append(n, fl[k]);\n"
    "          else this.append(n, new File([], '', {type: 'application/octet-stream'})); continue; }\n"
    "        this.append(n, (t === 'checkbox' || t === 'radio') ? (e.getAttribute('value') || 'on') : (e.value || '')); } } }\n"
    "  append(k, v, fn){ k = String(k); if (v instanceof Blob) this._l.push([k, v, fn !== undefined ? String(fn) : (v.name !== undefined ? v.name : 'blob')]); else this._l.push([k, String(v)]); }\n"
    "  set(k, v, fn){ this.delete(k); this.append(k, v, fn); }\n"
    "  get(k){ for (var p of this._l) if (p[0] === k) return p[1]; return null; }\n"
    "  getAll(k){ return this._l.filter(function(p){ return p[0] === k; }).map(function(p){ return p[1]; }); }\n"
    "  has(k){ return this.get(k) !== null; } delete(k){ this._l = this._l.filter(function(p){ return p[0] !== k; }); }\n"
    "  entries(){ return this._l.map(function(p){ return [p[0], p[1]]; })[Symbol.iterator](); }\n"
    "  keys(){ return this._l.map(function(p){ return p[0]; })[Symbol.iterator](); }\n"
    "  values(){ return this._l.map(function(p){ return p[1]; })[Symbol.iterator](); }\n"
    "  forEach(f, t){ var me = this; this._l.forEach(function(p){ f.call(t, p[1], p[0], me); }); }\n"
    "  [Symbol.iterator](){ return this.entries(); }\n"
    "};\n"
    "if (typeof Blob === 'undefined') W.Blob = class Blob {\n"
    "  constructor(parts, o){ this._s = (parts || []).map(function(p){ return p && p._path !== undefined ? __utf8_decode(__readFile(p._path) || new Uint8Array(0)) :\n"
    "      p && p._s !== undefined ? p._s : p && p.byteLength !== undefined && typeof p !== 'string' ? __utf8_decode(p) : String(p); }).join('');\n"
    "    this.type = (o && o.type) || ''; }\n"
    "  get size(){ return this._path !== undefined ? this._size : __utf8_encode(this._s).length; }\n"
    "  text(){ return Promise.resolve(this._s); }\n"
    "  arrayBuffer(){ return Promise.resolve(__utf8_encode(this._s).buffer); }\n"
    "  slice(a, b, t){ var r = new Blob([this._s.slice(a, b)]); r.type = t || ''; return r; }\n"
    "};\n"
    "if (W.crypto && crypto.getRandomValues) crypto.getRandomValues = function(a){ for (var i = 0; i < a.length; i++) a[i] = Math.floor(Math.random() * 4294967296); return a; };\n"
    "if (!Promise.withResolvers) Promise.withResolvers = function(){ var res, rej; var pr = new Promise(function(a, b){ res = a; rej = b; }); return {promise: pr, resolve: res, reject: rej}; };\n"
    "/* more DOM: element insertion helpers, popovers, tree walkers, ranges, events, parsing */\n"
    "var EPR = Element.prototype;\n"
    "/* shadow roots are their elements here: each has its own adopted sheets */\n"
    "if (!('adoptedStyleSheets' in EPR)) Object.defineProperty(EPR, 'adoptedStyleSheets', { configurable: true,\n"
    "  get: function(){ return this.__adopted || (this.__adopted = []); }, set: function(v){ this.__adopted = v; } });\n"
    "var toNode = function(x){ return typeof x === 'string' ? document.createTextNode(x) : x; };\n"
    "if (!EPR.before) EPR.before = function(){ var p = this.parentNode; if (!p) return; for (var i = 0; i < arguments.length; i++) p.insertBefore(toNode(arguments[i]), this); };\n"
    "if (!EPR.after) EPR.after = function(){ var p = this.parentNode; if (!p) return; var ref = this.nextSibling;\n"
    "  for (var i = 0; i < arguments.length; i++) { var n = toNode(arguments[i]); if (ref) p.insertBefore(n, ref); else p.appendChild(n); } };\n"
    "if (!EPR.showPopover) {\n"
    "  EPR.showPopover = function(){ this.removeAttribute('hidden'); this.setAttribute('data-popover-open', ''); };\n"
    "  EPR.hidePopover = function(){ this.removeAttribute('data-popover-open'); };\n"
    "  EPR.togglePopover = function(f){ var open = this.hasAttribute('data-popover-open'); if (f === undefined ? !open : f) this.showPopover(); else this.hidePopover(); return !open; };\n"
    "}\n"
    "if (!EPR.checkVisibility) EPR.checkVisibility = function(){ return true; };\n"
    "/* <template>.content: its children, moved into a fragment the first time */\n"
    "Object.defineProperty(EPR, 'content', { get: function(){\n"
    "  if (this.tagName !== 'TEMPLATE') return undefined;\n"
    "  if (!this.__frag) { var f = document.createDocumentFragment(); while (this.firstChild) f.appendChild(this.firstChild); this.__frag = f; }\n"
    "  return this.__frag; } });\n"
    "/* shadow DOM: the shadow root is the element itself, so what a web\n"
    " * component puts in it is laid out and shown like normal content */\n"
    "EPR.attachShadow = function(){ this.__shadow = this; return this; };\n"
    "Object.defineProperty(EPR, 'shadowRoot', { get: function(){ return this.__shadow || null; } });\n"
    "if (typeof W.ClipboardItem === 'undefined') W.ClipboardItem = class ClipboardItem {\n"
    "  constructor(items){ this.items = items || {}; this.types = Object.keys(this.items); }\n"
    "  getType(t){ return Promise.resolve(this.items[t]); }\n"
    "  static supports(){ return true; }\n"
    "};\n"
    "var NF = { FILTER_ACCEPT: 1, FILTER_REJECT: 2, FILTER_SKIP: 3, SHOW_ALL: 0xFFFFFFFF, SHOW_ELEMENT: 1, SHOW_ATTRIBUTE: 2,\n"
    "  SHOW_TEXT: 4, SHOW_COMMENT: 128, SHOW_DOCUMENT: 256, SHOW_DOCUMENT_FRAGMENT: 1024 };\n"
    "if (typeof NodeFilter === 'undefined') W.NodeFilter = NF;\n"
    "var showBit = function(n){ var t = n.nodeType; return t === 1 ? 1 : t === 3 ? 4 : t === 8 ? 128 : t === 9 ? 256 : t === 11 ? 1024 : 0; };\n"
    "var TreeWalker = function(root, what, filter){ this.root = root; this.whatToShow = what === undefined ? NF.SHOW_ALL : what; this.filter = filter || null; this.currentNode = root; };\n"
    "TreeWalker.prototype._ok = function(n){\n"
    "  if (!(this.whatToShow & showBit(n))) return 3;\n"
    "  if (!this.filter) return 1;\n"
    "  var f = typeof this.filter === 'function' ? this.filter : this.filter.acceptNode;\n"
    "  return f ? f.call(this.filter, n) : 1; };\n"
    "TreeWalker.prototype._next = function(n, skipKids){\n"
    "  if (!skipKids && n.firstChild) return n.firstChild;\n"
    "  while (n && n !== this.root) { if (n.nextSibling) return n.nextSibling; n = n.parentNode; }\n"
    "  return null; };\n"
    "TreeWalker.prototype.nextNode = function(){\n"
    "  var n = this.currentNode, skip = false;\n"
    "  for (;;) { n = this._next(n, skip); if (!n) return null; var r = this._ok(n); skip = r === 2; if (r === 1) { this.currentNode = n; return n; } } };\n"
    "TreeWalker.prototype.firstChild = function(){ var n = this.currentNode.firstChild; while (n && this._ok(n) !== 1) n = n.nextSibling; if (n) this.currentNode = n; return n || null; };\n"
    "TreeWalker.prototype.nextSibling = function(){ var n = this.currentNode.nextSibling; while (n && this._ok(n) !== 1) n = n.nextSibling; if (n) this.currentNode = n; return n || null; };\n"
    "TreeWalker.prototype.parentNode = function(){ var n = this.currentNode; while (n && n !== this.root) { n = n.parentNode; if (n && this._ok(n) === 1) { this.currentNode = n; return n; } } return null; };\n"
    "TreeWalker.prototype.previousNode = function(){ return null; };\n"
    "if (typeof W.TreeWalker === 'undefined') W.TreeWalker = TreeWalker;\n"
    "var DOC = document;\n"
    "if (!DOC.createTreeWalker) DOC.createTreeWalker = function(root, what, filter){ return new TreeWalker(root, what, filter); };\n"
    "if (!DOC.createNodeIterator) DOC.createNodeIterator = function(root, what, filter){ var w = new TreeWalker(root, what, filter); w.previousNode = function(){ return null; }; return w; };\n"
    "var DOMRect = function(x, y, w, h){ this.x = this.left = x || 0; this.y = this.top = y || 0; this.width = w || 0; this.height = h || 0;\n"
    "  this.right = this.x + this.width; this.bottom = this.y + this.height; };\n"
    "DOMRect.fromRect = function(r){ r = r || {}; return new DOMRect(r.x, r.y, r.width, r.height); };\n"
    "if (typeof W.DOMRect === 'undefined') { W.DOMRect = DOMRect; W.DOMRectReadOnly = DOMRect; }\n"
    "var Range = function(){ this.startContainer = this.endContainer = DOC; this.startOffset = this.endOffset = 0; this.collapsed = true; this.commonAncestorContainer = DOC; };\n"
    "Range.prototype.setStart = function(n, o){ this.startContainer = n; this.startOffset = o; };\n"
    "Range.prototype.setEnd = function(n, o){ this.endContainer = n; this.endOffset = o; this.collapsed = false; };\n"
    "Range.prototype.setStartBefore = Range.prototype.setStartAfter = Range.prototype.setEndBefore = Range.prototype.setEndAfter = function(n){ this.startContainer = n; };\n"
    "Range.prototype.selectNode = Range.prototype.selectNodeContents = function(n){ this.startContainer = this.endContainer = this.commonAncestorContainer = n; this.collapsed = false; };\n"
    "Range.prototype.collapse = function(){ this.collapsed = true; };\n"
    "Range.prototype.cloneRange = function(){ var r = new Range(); for (var k in this) if (this.hasOwnProperty(k)) r[k] = this[k]; return r; };\n"
    "Range.prototype.getBoundingClientRect = function(){ var n = this.startContainer; return n && n.getBoundingClientRect ? n.getBoundingClientRect() : new DOMRect(); };\n"
    "Range.prototype.getClientRects = function(){ return [this.getBoundingClientRect()]; };\n"
    "Range.prototype.toString = function(){ var n = this.startContainer; return n ? (n.textContent || '') : ''; };\n"
    "Range.prototype.createContextualFragment = function(html){ var t = DOC.createElement('template'); t.innerHTML = html;\n"
    "  var f = DOC.createDocumentFragment(); var src = t.content || t; while (src.firstChild) f.appendChild(src.firstChild); return f; };\n"
    "Range.prototype.deleteContents = Range.prototype.detach = function(){};\n"
    "Range.prototype.insertNode = function(n){ var c = this.startContainer; if (c && c.appendChild) c.appendChild(n); };\n"
    "if (typeof W.Range === 'undefined') W.Range = Range;\n"
    "if (!DOC.createRange) DOC.createRange = function(){ return new Range(); };\n"
    "if (!DOC.createEvent) DOC.createEvent = function(kind){\n"
    "  var e = new CustomEvent('');\n"
    "  e.initEvent = function(type, bubbles, cancelable){ this.type = type; this.bubbles = !!bubbles; this.cancelable = !!cancelable; };\n"
    "  e.initCustomEvent = function(type, bubbles, cancelable, detail){ this.initEvent(type, bubbles, cancelable); this.detail = detail; };\n"
    "  return e; };\n"
    "if (!DOC.importNode) DOC.importNode = function(n, deep){ return n.cloneNode(!!deep); };\n"
    "if (!DOC.adoptNode) DOC.adoptNode = function(n){ if (n.parentNode) n.parentNode.removeChild(n); return n; };\n"
    "if (!DOC.elementFromPoint) DOC.elementFromPoint = function(){ return null; };\n"
    "if (!DOC.elementsFromPoint) DOC.elementsFromPoint = function(){ return []; };\n"
    "if (!DOC.startViewTransition) DOC.startViewTransition = function(cb){ var p = Promise.resolve().then(function(){ return cb && cb(); });\n"
    "  return { finished: p, ready: Promise.resolve(), updateCallbackDone: p, skipTransition: function(){} }; };\n"
    "if (typeof W.DOMParser === 'undefined') W.DOMParser = class DOMParser {\n"
    "  parseFromString(s){ var html = DOC.createElement('html'); html.innerHTML = String(s);\n"
    "    var body = html.querySelector('body') || html, head = html.querySelector('head') || DOC.createElement('head');\n"
    "    return { documentElement: html, body: body, head: head, title: (html.querySelector('title') || {}).textContent || '',\n"
    "      querySelector: function(q){ return html.querySelector(q); }, querySelectorAll: function(q){ return html.querySelectorAll(q); },\n"
    "      getElementById: function(id){ return html.querySelector('#' + id); }, getElementsByTagName: function(t){ return html.querySelectorAll(t); },\n"
    "      createElement: function(t){ return DOC.createElement(t); } }; }\n"
    "};\n"
    "if (typeof W.XMLSerializer === 'undefined') W.XMLSerializer = class XMLSerializer { serializeToString(n){ return n.outerHTML !== undefined ? n.outerHTML : String(n.textContent || ''); } };\n"
    "if (typeof W.Option === 'undefined') W.Option = function(text, value, def, sel){ var o = DOC.createElement('option');\n"
    "  if (text !== undefined) o.textContent = text; if (value !== undefined) o.setAttribute('value', value); if (sel) o.setAttribute('selected', ''); return o; };\n"
    "if (typeof W.FinalizationRegistry === 'undefined') W.FinalizationRegistry = class FinalizationRegistry { register(){} unregister(){ return false; } };\n"
    "if (typeof W.BroadcastChannel === 'undefined') W.BroadcastChannel = class BroadcastChannel { constructor(n){ this.name = n; this.onmessage = null; }\n"
    "  postMessage(){} close(){} addEventListener(){} removeEventListener(){} };\n"
    "if (typeof W.File === 'undefined' && typeof Blob !== 'undefined') W.File = class File extends Blob {\n"
    "  constructor(parts, name, o){ super(parts, o); this.name = String(name); this.lastModified = Date.now(); } };\n"
    "if (typeof W.FileReader === 'undefined') W.FileReader = class FileReader {\n"
    "  constructor(){ this.result = null; this.readyState = 0; this.onload = this.onloadend = this.onerror = null; }\n"
    "  _done(r){ var me = this; me.result = r; me.readyState = 2; setTimeout(function(){ var e = {type: 'load', target: me};\n"
    "    if (me.onload) me.onload(e); if (me.onloadend) me.onloadend(e); }, 0); }\n"
    "  readAsText(b){ this._done(__blobStr(b)); }\n"
    "  readAsDataURL(b){ this._done('data:' + ((b && b.type) || 'application/octet-stream') + ';base64,' + btoa(__blobStr(b))); }\n"
    "  readAsArrayBuffer(b){ this._done((b && b._path !== undefined ? (__readFile(b._path) || new Uint8Array(0)) : __utf8_encode(__blobStr(b))).buffer); }\n"
    "  readAsBinaryString(b){ this._done(__blobStr(b)); }\n"
    "  abort(){} addEventListener(t, f){ if (t === 'load') this.onload = f; else if (t === 'loadend') this.onloadend = f; else if (t === 'error') this.onerror = f; }\n"
    "};\n"
    "if (typeof W.Response === 'undefined') W.Response = class Response {\n"
    "  constructor(body, init){ init = init || {}; this._b = body == null ? '' : (typeof body === 'string' ? body : body._s !== undefined ? body._s : String(body));\n"
    "    this.status = init.status === undefined ? 200 : init.status; this.statusText = init.statusText || ''; this.ok = this.status >= 200 && this.status < 300;\n"
    "    this.headers = new Headers(init.headers); this.url = ''; this.type = 'default'; this.redirected = false; this.bodyUsed = false; }\n"
    "  text(){ return Promise.resolve(this._b); }\n"
    "  json(){ var me = this; return Promise.resolve().then(function(){ return JSON.parse(me._b); }); }\n"
    "  blob(){ return Promise.resolve(new Blob([this._b])); }\n"
    "  arrayBuffer(){ return Promise.resolve(__utf8_encode(this._b).buffer); }\n"
    "  clone(){ return new Response(this._b, {status: this.status, statusText: this.statusText, headers: this.headers}); }\n"
    "  static json(d, init){ return new Response(JSON.stringify(d), init); }\n"
    "  static error(){ return new Response('', {status: 0}); }\n"
    "};\n"
    "if (typeof W.Request === 'undefined') W.Request = class Request {\n"
    "  constructor(input, init){ init = init || {}; this.url = typeof input === 'string' ? input : input.url; this.method = (init.method || 'GET').toUpperCase();\n"
    "    this.headers = new Headers(init.headers); this.body = init.body === undefined ? null : init.body; this.credentials = init.credentials || 'same-origin';\n"
    "    this.mode = init.mode || 'cors'; this.signal = init.signal || null; }\n"
    "  clone(){ return new Request(this.url, this); }\n"
    "};\n"
    "if (typeof W.Intl === 'undefined') {\n"
    "  var pad2 = function(n){ return (n < 10 ? '0' : '') + n; };\n"
    "  var MON = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];\n"
    "  var DTF = function(loc, o){ this.o = o || {}; };\n"
    "  DTF.prototype.format = function(d){ d = d === undefined ? new Date() : (d instanceof Date ? d : new Date(d)); var o = this.o;\n"
    "    if (o.hour !== undefined && o.year === undefined && o.month === undefined) return pad2(d.getHours()) + ':' + pad2(d.getMinutes());\n"
    "    var s = MON[d.getMonth()] + ' ' + d.getDate() + ', ' + d.getFullYear();\n"
    "    if (o.hour !== undefined) s += ', ' + pad2(d.getHours()) + ':' + pad2(d.getMinutes());\n"
    "    return s; };\n"
    "  DTF.prototype.formatToParts = function(d){ return [{type: 'literal', value: this.format(d)}]; };\n"
    "  DTF.prototype.resolvedOptions = function(){ return {locale: 'en-US', timeZone: 'UTC', calendar: 'gregory', numberingSystem: 'latn'}; };\n"
    "  var NFm = function(loc, o){ this.o = o || {}; };\n"
    "  NFm.prototype.format = function(n){ var o = this.o, x = Number(n);\n"
    "    if (o.maximumFractionDigits !== undefined) x = Number(x.toFixed(o.maximumFractionDigits));\n"
    "    var s = x.toLocaleString(); if (o.style === 'percent') s = (x * 100).toFixed(0) + '%';\n"
    "    if (o.style === 'currency') s = (o.currency === 'EUR' ? '€' : '$') + x.toFixed(2);\n"
    "    return s; };\n"
    "  NFm.prototype.formatToParts = function(n){ return [{type: 'integer', value: this.format(n)}]; };\n"
    "  NFm.prototype.resolvedOptions = function(){ return {locale: 'en-US'}; };\n"
    "  var RTF = function(){};\n"
    "  RTF.prototype.format = function(v, unit){ v = Number(v); var u = String(unit).replace(/s$/, ''), a = Math.abs(v);\n"
    "    var w = a + ' ' + u + (a === 1 ? '' : 's'); return v < 0 ? w + ' ago' : 'in ' + w; };\n"
    "  var PR = function(){}; PR.prototype.select = function(n){ return n === 1 ? 'one' : 'other'; };\n"
    "  var COL = function(){}; COL.prototype.compare = function(a, b){ a = String(a); b = String(b); return a < b ? -1 : a > b ? 1 : 0; };\n"
    "  var LF = function(){}; LF.prototype.format = function(l){ l = Array.from(l); return l.length < 2 ? l.join('') : l.slice(0, -1).join(', ') + ' and ' + l[l.length - 1]; };\n"
    "  W.Intl = { DateTimeFormat: DTF, NumberFormat: NFm, RelativeTimeFormat: RTF, PluralRules: PR, Collator: COL, ListFormat: LF,\n"
    "    getCanonicalLocales: function(l){ return l ? [].concat(l) : []; },\n"
    "    Segmenter: function(){ this.segment = function(s){ return Array.from(String(s)).map(function(c, i){ return {segment: c, index: i}; }); }; } };\n"
    "  if (Date.prototype) Date.prototype.toLocaleDateString = function(){ return new DTF().format(this); };\n"
    "}\n"
    "if (typeof W.DOMException === 'undefined') {\n"
    "  var DE_CODES = { IndexSizeError: 1, HierarchyRequestError: 3, WrongDocumentError: 4, InvalidCharacterError: 5,\n"
    "    NoModificationAllowedError: 7, NotFoundError: 8, NotSupportedError: 9, InvalidStateError: 11, SyntaxError: 12,\n"
    "    InvalidModificationError: 13, NamespaceError: 14, InvalidAccessError: 15, TypeMismatchError: 17, SecurityError: 18,\n"
    "    NetworkError: 19, AbortError: 20, URLMismatchError: 21, QuotaExceededError: 22, TimeoutError: 23,\n"
    "    InvalidNodeTypeError: 24, DataCloneError: 25 };\n"
    "  W.DOMException = class DOMException extends Error {\n"
    "    constructor(message, name) { super(message === undefined ? '' : String(message)); this.message = message === undefined ? '' : String(message); this.name = name || 'Error'; this.code = DE_CODES[this.name] || 0; }\n"
    "  };\n"
    "  for (var dk in DE_CODES) W.DOMException[dk.replace(/([a-z])([A-Z])/g, '$1_$2').toUpperCase().replace(/_ERROR$/, '_ERR')] = DE_CODES[dk];\n"
    "}\n"
    "(function(N){\n"
    "  if (!N) return;\n"
    "  var def = function(k, v){ if (N[k] === undefined) N[k] = v; };\n"
    "  def('languages', [N.language || 'en-US', 'en']);\n"
    "  def('hardwareConcurrency', 1); def('maxTouchPoints', 0); def('deviceMemory', 4);\n"
    "  def('vendor', ''); def('product', 'Gecko'); def('appCodeName', 'Mozilla'); def('appVersion', '5.0 (Banana OS)');\n"
    "  def('doNotTrack', null); def('webdriver', false); def('pdfViewerEnabled', false);\n"
    "  def('plugins', []); def('mimeTypes', []);\n"
    "  def('connection', { effectiveType: '4g', downlink: 10, rtt: 50, saveData: false, addEventListener: function(){}, removeEventListener: function(){} });\n"
    "  def('sendBeacon', function(){ return true; });\n"
    "  def('vibrate', function(){ return false; });\n"
    "  def('javaEnabled', function(){ return false; });\n"
    "  def('clipboard', { writeText: function(){ return Promise.resolve(); }, readText: function(){ return Promise.resolve(''); },\n"
    "                     write: function(){ return Promise.resolve(); }, read: function(){ return Promise.resolve([]); } });\n"
    "  def('permissions', { query: function(){ return Promise.resolve({ state: 'prompt', onchange: null, addEventListener: function(){} }); } });\n"
    "  def('storage', { estimate: function(){ return Promise.resolve({ quota: 0, usage: 0 }); }, persist: function(){ return Promise.resolve(false); } });\n"
    "})(W.navigator);\n"
    "/* web views: the app's web_post(text) arrives as a \"message\" event */\n"
    "W.__banana_deliver = function(data){\n"
    "  var e; try { e = new MessageEvent('message', { data: data, origin: 'banana:' }); } catch (x) { e = new Event('message'); e.data = data; e.origin = 'banana:'; }\n"
    "  if (typeof W.onmessage === 'function') { try { W.onmessage(e); } catch (x) {} }\n"
    "  W.dispatchEvent(e);\n"
    "};\n"
    "/* <audio> / <video> / new Audio(): sound through the system's media streams\n"
    " * (__media_*: kernel/media.c). The element's state lives in el.__ms; a timer\n"
    " * polls the stream and fires the usual events. */\n"
    "(function(){\n"
    "  if (typeof __media_open !== 'function') { W.Audio = W.Audio || function(src){ var a = document.createElement('audio'); if (src !== undefined) a.setAttribute('src', src); return a; }; return; }\n"
    "  var PLAY = 1, PAUSE = 2, SEEK = 3, SET = 4, CLOSE = 5;\n"
    "  function isMedia(el){ var t = el && el.tagName; return t === 'AUDIO' || t === 'VIDEO'; }\n"
    "  function st(el){\n"
    "    return el.__ms || (el.__ms = { id: -1, url: '', vol: 1, muted: false, loop: false, paused: true, ended: false,\n"
    "                                   pos: 0, dur: NaN, ready: 0, seq: 0, rate: 1, err: null, seeking: false, playing: false });\n"
    "  }\n"
    "  function srcOf(el){\n"
    "    var s = el.getAttribute('src');\n"
    "    if (!s) { var so = el.querySelector('source[src]'); if (so) s = so.getAttribute('src'); }\n"
    "    if (!s) return '';\n"
    "    try { return new URL(s, location.href).href; } catch (x) { return s; }\n"
    "  }\n"
    "  function fire(el, type){ try { el.dispatchEvent(new Event(type)); } catch (x) {} }\n"
    "  var active = [], timer = 0;\n"
    "  function track(el){ if (active.indexOf(el) < 0) active.push(el); if (!timer) timer = setInterval(poll, 250); }\n"
    "  function pushSet(el){ var m = st(el); if (m.id >= 0) __media_cmd(m.id, SET, Math.round(m.vol * 100), m.muted ? 1 : 0, (m.loop || el.hasAttribute('loop')) ? 1 : 0); }\n"
    "  function ensure(el){\n"
    "    var m = st(el), u = srcOf(el);\n"
    "    if (u && u !== m.url) {\n"
    "      if (m.id >= 0) __media_cmd(m.id, CLOSE);\n"
    "      m.url = u; m.id = __media_open(u); m.ready = 0; m.dur = NaN; m.pos = 0; m.ended = false; m.err = null;\n"
    "      pushSet(el);\n"
    "      fire(el, 'loadstart');\n"
    "      track(el);\n"
    "    }\n"
    "    return m;\n"
    "  }\n"
    "  function poll(){\n"
    "    for (var i = 0; i < active.length; i++) {\n"
    "      var el = active[i], m = st(el);\n"
    "      if (m.id < 0) continue;\n"
    "      var s = __media_status(m.id);\n"
    "      if (!s) continue;\n"
    "      if (s.state === 2 && m.ready < 4) {\n"
    "        m.ready = 4; m.dur = s.dur;\n"
    "        fire(el, 'durationchange'); fire(el, 'loadedmetadata'); fire(el, 'loadeddata'); fire(el, 'canplay'); fire(el, 'canplaythrough');\n"
    "        if (m.paused && el.hasAttribute('autoplay')) el.play();\n"
    "      }\n"
    "      if (s.state === 3 && !m.err) { m.err = { code: 4, message: s.error, MEDIA_ERR_SRC_NOT_SUPPORTED: 4 }; m.paused = true; fire(el, 'error'); }\n"
    "      if (s.playing && !m.playing) { m.playing = true; fire(el, 'playing'); }\n"
    "      if (!s.playing) m.playing = false;\n"
    "      if (s.pos !== m.pos && !m.seeking) { m.pos = s.pos; fire(el, 'timeupdate'); }\n"
    "      if (s.seq !== m.seq) { m.seq = s.seq; if (m.seeking) { m.seeking = false; m.pos = s.pos; fire(el, 'seeked'); fire(el, 'timeupdate'); } }\n"
    "      if (s.ended && !m.ended && !m.paused) { m.ended = true; m.paused = true; m.pos = m.dur; fire(el, 'timeupdate'); fire(el, 'pause'); fire(el, 'ended'); }\n"
    "    }\n"
    "  }\n"
    "  EPR.play = function(){\n"
    "    if (!isMedia(this)) return Promise.resolve();\n"
    "    var m = ensure(this);\n"
    "    if (m.id < 0) return Promise.reject(new DOMException('The element has no supported sources.', 'NotSupportedError'));\n"
    "    if (m.paused) { m.paused = false; m.ended = false; __media_cmd(m.id, PLAY); fire(this, 'play'); }\n"
    "    return Promise.resolve();\n"
    "  };\n"
    "  EPR.pause = function(){\n"
    "    if (!isMedia(this)) return;\n"
    "    var m = st(this);\n"
    "    if (m.paused) return;\n"
    "    m.paused = true;\n"
    "    if (m.id >= 0) __media_cmd(m.id, PAUSE);\n"
    "    fire(this, 'pause');\n"
    "  };\n"
    "  EPR.load = function(){ if (!isMedia(this)) return; var m = st(this); m.url = ''; m.paused = true; ensure(this); };\n"
    "  EPR.canPlayType = function(t){\n"
    "    t = String(t || '').toLowerCase();\n"
    "    return /audio\\/(mpeg|mp3|mpeg3|x-mpeg|wav|wave|x-wav|flac|x-flac)/.test(t) ? 'probably' : '';\n"
    "  };\n"
    "  EPR.fastSeek = function(t){ this.currentTime = t; };\n"
    "  function prop(name, get, set){\n"
    "    Object.defineProperty(EPR, name, { configurable: true,\n"
    "      get: function(){ return isMedia(this) ? get.call(this, st(this)) : this['__' + name]; },\n"
    "      set: function(v){ if (isMedia(this) && set) set.call(this, st(this), v); else this['__' + name] = v; } });\n"
    "  }\n"
    "  prop('currentTime', function(m){ return m.pos; }, function(m, v){\n"
    "    v = +v || 0; if (v < 0) v = 0;\n"
    "    var mm = ensure(this); m.pos = v; m.seeking = true; m.ended = false;\n"
    "    fire(this, 'seeking');\n"
    "    if (mm.id >= 0) __media_cmd(mm.id, SEEK, Math.round(v * 1000));\n"
    "  });\n"
    "  prop('duration', function(m){ return m.dur; });\n"
    "  prop('paused', function(m){ return m.paused; });\n"
    "  prop('ended', function(m){ return m.ended; });\n"
    "  prop('volume', function(m){ return m.vol; }, function(m, v){ m.vol = Math.max(0, Math.min(1, +v || 0)); pushSet(this); fire(this, 'volumechange'); });\n"
    "  prop('muted', function(m){ return m.muted; }, function(m, v){ m.muted = !!v; pushSet(this); fire(this, 'volumechange'); });\n"
    "  prop('loop', function(m){ return m.loop || this.hasAttribute('loop'); }, function(m, v){ m.loop = !!v; pushSet(this); });\n"
    "  prop('autoplay', function(m){ return this.hasAttribute('autoplay'); }, function(m, v){ if (v) this.setAttribute('autoplay', ''); else this.removeAttribute('autoplay'); });\n"
    "  prop('readyState', function(m){ return m.ready; });\n"
    "  prop('networkState', function(m){ return m.id < 0 ? 0 : m.ready ? 1 : 2; });\n"
    "  prop('error', function(m){ return m.err; });\n"
    "  prop('seeking', function(m){ return m.seeking; });\n"
    "  prop('playbackRate', function(m){ return m.rate; }, function(m, v){ m.rate = +v || 1; });\n"
    "  prop('defaultPlaybackRate', function(m){ return 1; }, function(m, v){});\n"
    "  prop('currentSrc', function(m){ return m.url; });\n"
    "  prop('preload', function(m){ return this.getAttribute('preload') || 'auto'; }, function(m, v){ this.setAttribute('preload', v); });\n"
    "  prop('buffered', function(m){ var d = m.ready ? m.dur : 0, n = m.ready ? 1 : 0;\n"
    "    return { length: n, start: function(){ return 0; }, end: function(){ return d; } }; });\n"
    "  prop('played', function(m){ return { length: 0, start: function(){ return 0; }, end: function(){ return 0; } }; });\n"
    "  prop('seekable', function(m){ var d = m.ready ? m.dur : 0, n = m.ready ? 1 : 0;\n"
    "    return { length: n, start: function(){ return 0; }, end: function(){ return d; } }; });\n"
    "  /* src: an attribute; a new one loads when it plays (or now, with autoplay / preload) */\n"
    "  W.Audio = function(src){ var a = document.createElement('audio'); if (src !== undefined) a.setAttribute('src', src); return a; };\n"
    "  W.Audio.prototype = EPR;\n"
    "  if (W.HTMLMediaElement) { W.HTMLMediaElement.HAVE_NOTHING = 0; W.HTMLMediaElement.HAVE_METADATA = 1; W.HTMLMediaElement.HAVE_ENOUGH_DATA = 4; }\n"
    "  if (typeof W.HTMLAudioElement === 'undefined') W.HTMLAudioElement = W.Audio;\n"
    "  if (typeof W.MediaMetadata === 'undefined') W.MediaMetadata = function(o){ o = o || {}; this.title = o.title || ''; this.artist = o.artist || ''; this.album = o.album || ''; this.artwork = o.artwork || []; };\n"
    "  if (W.navigator && !W.navigator.mediaSession) W.navigator.mediaSession = { metadata: null, playbackState: 'none', setActionHandler: function(){}, setPositionState: function(){} };\n"
    "})();\n"
    "})();\n"
    "\n"
    "/* PerformanceObserver.supportedEntryTypes: pages ask before observing */\n"
    "try { if (typeof PerformanceObserver !== 'undefined' && !PerformanceObserver.supportedEntryTypes) PerformanceObserver.supportedEntryTypes = []; } catch (e) {}\n"
    "\n"
    "/* uploads: the file chosen in an <input type=file> is a File read from the\n"
    " * disk when sent (FormData + fetch / XMLHttpRequest) or read (text(), FileReader) */\n"
    "window.__blobStr = function(b){ return b && b._path !== undefined ? __utf8_decode(__readFile(b._path) || new Uint8Array(0)) : (b && b._s !== undefined ? b._s : String(b)); };\n"
    "window.FileList = class FileList { constructor(a){ a = a || []; for (var i = 0; i < a.length; i++) this[i] = a[i]; this.length = a.length; }\n"
    "  item(i){ return this[i] || null; } [Symbol.iterator](){ return Array.prototype.slice.call(this)[Symbol.iterator](); } };\n"
    "(function(){\n"
    "  var BP = Blob.prototype;\n"
    "  BP.text = function(){ return Promise.resolve(__blobStr(this)); };\n"
    "  BP.arrayBuffer = function(){ return Promise.resolve((this._path !== undefined ? (__readFile(this._path) || new Uint8Array(0)) : __utf8_encode(this._s)).buffer); };\n"
    "  BP.bytes = function(){ return Promise.resolve(this._path !== undefined ? (__readFile(this._path) || new Uint8Array(0)) : __utf8_encode(this._s)); };\n"
    "  BP.slice = function(a, b, t){ var r = new Blob([]); r._s = __blobStr(this).slice(a, b); r.type = t || ''; return r; };\n"
    "  BP.stream = function(){ var me = this; return { getReader: function(){ var done = false; return { read: function(){\n"
    "    if (done) return Promise.resolve({done: true, value: undefined}); done = true;\n"
    "    return me.bytes().then(function(v){ return {done: false, value: v}; }); }, releaseLock: function(){}, cancel: function(){ return Promise.resolve(); } }; } }; };\n"
    "  Object.defineProperty(Element.prototype, 'files', { configurable: true,\n"
    "    get: function(){ if (this.tagName !== 'INPUT' || (this.getAttribute('type') || '').toLowerCase() !== 'file') return undefined;\n"
    "      return this.__files || (this.__files = new FileList()); },\n"
    "    set: function(v){ this.__files = v; } });\n"
    "})();\n"
    "window.__setFiles = function(el, path, name, size, type){\n"
    "  var f = Object.create(File.prototype); f._path = path; f.name = name; f.type = type || ''; f.lastModified = Date.now(); f.webkitRelativePath = '';\n"
    "  f._size = size;\n"
    "  el.__files = new FileList([f]);\n"
    "  el.dispatchEvent(new Event('input', {bubbles: true}));\n"
    "  el.dispatchEvent(new Event('change', {bubbles: true}));\n"
    "};\n"
    "/* document.implementation: detached documents (jQuery builds HTML in one) */\n"
    "try { if (!document.implementation || !document.implementation.createHTMLDocument) document.implementation = {\n"
    "  createHTMLDocument: function(t){ var d = new DOMParser().parseFromString(\"\"); d.title = t || \"\"; return d; },\n"
    "  createDocument: function(){ return new DOMParser().parseFromString(\"\"); },\n"
    "  createDocumentType: function(){ return null; }, hasFeature: function(){ return true; } }; } catch (e) {}\n"
    "try { if (typeof document.close !== 'function') document.close = function(){}; if (typeof document.open !== 'function') document.open = function(){ return document; }; } catch (e) {}\n"
;
