/* generated from web/prelude.js by web/test/embed.pl: do not edit */
static const char k_prelude[] =
    "/* Run in every page before its own scripts: the web APIs that are easier to\n"
    " * write in script than in C.  web/prelude.h is generated from this file by\n"
    " * web/test/embed.pl. */\n"
    "(function(){\n"
    "var W = window, P = performance, marks = [];\n"
    "P.mark = function(n){ var e = {name:n, entryType:'mark', startTime:P.now(), duration:0}; marks.push(e); return e; };\n"
    "P.measure = function(n){ var e = {name:n, entryType:'measure', startTime:0, duration:P.now()}; marks.push(e); return e; };\n"
    "P.getEntriesByName = function(n){ return marks.filter(function(e){ return e.name === n; }); };\n"
    "P.getEntriesByType = function(t){ return marks.filter(function(e){ return e.entryType === t; }); };\n"
    "P.getEntries = function(){ return marks.slice(); };\n"
    "P.clearMarks = P.clearMeasures = function(){ marks = []; };\n"
    "P.timeOrigin = 0; P.timing = {navigationStart:0}; P.navigation = {type:0};\n"
    "function enc(s){ return encodeURIComponent(s).replace(/%20/g, '+'); }\n"
    "function dec(s){ try { return decodeURIComponent(s.replace(/\\+/g, ' ')); } catch (e) { return s; } }\n"
    "class URLSearchParams {\n"
    "  constructor(init){ this._l = []; if (init == null) return;\n"
    "    if (typeof init === 'object') {\n"
    "      if (Array.isArray(init)) { for (var p of init) this._l.push([String(p[0]), String(p[1])]); }\n"
    "      else if (init._l) { this._l = init._l.map(function(p){ return [p[0], p[1]]; }); }\n"
    "      else { for (var k in init) this._l.push([k, String(init[k])]); }\n"
    "      return; }\n"
    "    var s = String(init); if (s[0] === '?') s = s.slice(1);\n"
    "    for (var part of s.split('&')) { if (!part) continue; var i = part.indexOf('=');\n"
    "      this._l.push(i < 0 ? [dec(part), ''] : [dec(part.slice(0, i)), dec(part.slice(i + 1))]); } }\n"
    "  get(k){ for (var p of this._l) if (p[0] === k) return p[1]; return null; }\n"
    "  getAll(k){ return this._l.filter(function(p){ return p[0] === k; }).map(function(p){ return p[1]; }); }\n"
    "  has(k){ return this.get(k) !== null; }\n"
    "  set(k, v){ var done = false; this._l = this._l.filter(function(p){ if (p[0] !== k) return true; if (done) return false; p[1] = String(v); done = true; return true; });\n"
    "    if (!done) this._l.push([k, String(v)]); if (this._u) this._u._sync(); }\n"
    "  append(k, v){ this._l.push([k, String(v)]); if (this._u) this._u._sync(); }\n"
    "  delete(k){ this._l = this._l.filter(function(p){ return p[0] !== k; }); if (this._u) this._u._sync(); }\n"
    "  forEach(f, t){ for (var p of this._l) f.call(t, p[1], p[0], this); }\n"
    "  keys(){ return this._l.map(function(p){ return p[0]; })[Symbol.iterator](); }\n"
    "  values(){ return this._l.map(function(p){ return p[1]; })[Symbol.iterator](); }\n"
    "  entries(){ return this._l.map(function(p){ return [p[0], p[1]]; })[Symbol.iterator](); }\n"
    "  [Symbol.iterator](){ return this.entries(); }\n"
    "  get size(){ return this._l.length; }\n"
    "  sort(){ this._l.sort(function(a, b){ return a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0; }); }\n"
    "  toString(){ return this._l.map(function(p){ return enc(p[0]) + '=' + enc(p[1]); }).join('&'); }\n"
    "}\n"
    "function resolve(u, base){\n"
    "  if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(u)) return u;\n"
    "  if (base == null) throw new TypeError('Invalid URL: ' + u);\n"
    "  var b = new URL(String(base));\n"
    "  if (u.slice(0, 2) === '//') return b.protocol + u;\n"
    "  if (u[0] === '/') return b.origin + u;\n"
    "  if (u[0] === '?') return b.origin + b.pathname + u;\n"
    "  if (u[0] === '#') return b.origin + b.pathname + b.search + u;\n"
    "  if (u === '') return b.origin + b.pathname + b.search;\n"
    "  var dir = b.pathname.slice(0, b.pathname.lastIndexOf('/') + 1), segs = (dir + u).split('/'), out = [];\n"
    "  for (var i = 0; i < segs.length; i++) { var s = segs[i];\n"
    "    if (s === '..') { if (out.length > 1) out.pop(); if (i === segs.length - 1) out.push(''); }\n"
    "    else if (s === '.') { if (i === segs.length - 1) out.push(''); }\n"
    "    else out.push(s); }\n"
    "  return b.origin + out.join('/');\n"
    "}\n"
    "var URL_RX = /^([a-zA-Z][a-zA-Z0-9+.-]*:)(?:\\/\\/(?:([^:@\\/]*)(?::([^@\\/]*))?@)?([^:\\/?#]*)(?::(\\d+))?)?([^?#]*)(\\?[^#]*)?(#.*)?$/;\n"
    "class URL {\n"
    "  constructor(u, base){ this._set(resolve(String(u), base)); }\n"
    "  _set(s){\n"
    "    var m = URL_RX.exec(s);\n"
    "    if (!m) throw new TypeError('Invalid URL: ' + s);\n"
    "    this.protocol = m[1].toLowerCase(); this.username = m[2] || ''; this.password = m[3] || '';\n"
    "    this.hostname = (m[4] || '').toLowerCase(); this.port = m[5] || '';\n"
    "    this.pathname = m[6] || (m[4] != null ? '/' : '');\n"
    "    this.search = m[7] && m[7] !== '?' ? m[7] : ''; this.hash = m[8] && m[8] !== '#' ? m[8] : '';\n"
    "    this.searchParams = new URLSearchParams(this.search); this.searchParams._u = this;\n"
    "  }\n"
    "  _sync(){ var q = this.searchParams.toString(); this.search = q ? '?' + q : ''; }\n"
    "  get host(){ return this.hostname + (this.port ? ':' + this.port : ''); }\n"
    "  get origin(){ return this.protocol + '//' + this.host; }\n"
    "  get href(){ return this.origin + this.pathname + this.search + this.hash; }\n"
    "  set href(v){ this._set(String(v)); }\n"
    "  toString(){ return this.href; }\n"
    "  toJSON(){ return this.href; }\n"
    "  static canParse(u, b){ try { new URL(u, b); return true; } catch (e) { return false; } }\n"
    "  static createObjectURL(){ return 'blob:null'; }\n"
    "  static revokeObjectURL(){}\n"
    "}\n"
    "W.URL = URL; W.URLSearchParams = URLSearchParams;\n"
    "\n"
    "/* event targets that are not elements (signals, ports, `class X extends EventTarget`) */\n"
    "class EventTarget {\n"
    "  addEventListener(t, f, o){ if (!f) return; var l = this.__ls || (this.__ls = {});\n"
    "    (l[t] || (l[t] = [])).push({f: f, once: !!(o && typeof o === 'object' && o.once)}); }\n"
    "  removeEventListener(t, f){ var l = this.__ls && this.__ls[t]; if (l) this.__ls[t] = l.filter(function(x){ return x.f !== f; }); }\n"
    "  dispatchEvent(ev){\n"
    "    try { if (!ev.target) ev.target = this; ev.currentTarget = this; } catch (e) {}\n"
    "    var h = this['on' + ev.type]; if (typeof h === 'function') h.call(this, ev);\n"
    "    var l = this.__ls && this.__ls[ev.type];\n"
    "    if (l) for (var x of l.slice()) {\n"
    "      if (x.once) this.removeEventListener(ev.type, x.f);\n"
    "      if (typeof x.f === 'function') x.f.call(this, ev); else if (x.f && x.f.handleEvent) x.f.handleEvent(ev);\n"
    "    }\n"
    "    return !ev.defaultPrevented;\n"
    "  }\n"
    "}\n"
    "class AbortSignal extends EventTarget {\n"
    "  constructor(){ super(); this.aborted = false; this.reason = undefined; this.onabort = null; }\n"
    "  throwIfAborted(){ if (this.aborted) throw this.reason; }\n"
    "  static abort(r){ var c = new AbortController(); c.abort(r); return c.signal; }\n"
    "  static timeout(ms){ var c = new AbortController(); setTimeout(function(){ c.abort(new Error('TimeoutError')); }, ms); return c.signal; }\n"
    "  static any(list){ var c = new AbortController();\n"
    "    for (var s of list) { if (s.aborted) { c.abort(s.reason); break; } s.addEventListener('abort', function(){ c.abort(this.reason); }); }\n"
    "    return c.signal; }\n"
    "}\n"
    "class AbortController {\n"
    "  constructor(){ this.signal = new AbortSignal(); }\n"
    "  abort(r){ var s = this.signal; if (s.aborted) return; s.aborted = true;\n"
    "    s.reason = r === undefined ? new Error('AbortError') : r; s.dispatchEvent({type: 'abort', target: s}); }\n"
    "}\n"
    "/* MessageChannel: messages arrive on the next turn (React's scheduler uses it) */\n"
    "class MessagePort extends EventTarget {\n"
    "  constructor(){ super(); this.onmessage = null; this._other = null; }\n"
    "  postMessage(d){ var o = this._other; setTimeout(function(){ o.dispatchEvent({type: 'message', data: d}); }, 0); }\n"
    "  start(){} close(){}\n"
    "}\n"
    "class MessageChannel {\n"
    "  constructor(){ this.port1 = new MessagePort(); this.port2 = new MessagePort(); this.port1._other = this.port2; this.port2._other = this.port1; }\n"
    "}\n"
    "W.EventTarget = EventTarget; W.AbortSignal = AbortSignal; W.AbortController = AbortController;\n"
    "W.MessagePort = MessagePort; W.MessageChannel = MessageChannel;\n"
    "var EP = Element.prototype;\n"
    "if (!EP.getRootNode) EP.getRootNode = function(){ var n = this; while (n.parentNode) n = n.parentNode; return n; };\n"
    "if (typeof crypto === 'undefined') W.crypto = {\n"
    "  getRandomValues: function(a){ for (var i = 0; i < a.length; i++) a[i] = Math.floor(Math.random() * 256); return a; },\n"
    "  randomUUID: function(){ return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c){\n"
    "    var r = Math.floor(Math.random() * 16); return (c === 'x' ? r : (r & 3) | 8).toString(16); }); },\n"
    "  subtle: {}\n"
    "};\n"
    "var D = document;\n"
    "if (!D.styleSheets) D.styleSheets = [];\n"
    "if (!D.adoptedStyleSheets) D.adoptedStyleSheets = [];\n"
    "if (!D.fonts) D.fonts = { ready: Promise.resolve(), status: 'loaded', check: function(){ return true; },\n"
    "  load: function(){ return Promise.resolve([]); }, add: function(){}, delete: function(){}, forEach: function(){},\n"
    "  addEventListener: function(){}, removeEventListener: function(){} };\n"
    "if (typeof CSSStyleSheet === 'undefined') W.CSSStyleSheet = class CSSStyleSheet {\n"
    "  constructor(){ this.cssRules = []; } replaceSync(t){ this.text = t; } replace(t){ this.text = t; return Promise.resolve(this); }\n"
    "  insertRule(r, i){ this.cssRules.splice(i || 0, 0, {cssText: r}); return i || 0; } deleteRule(i){ this.cssRules.splice(i, 1); }\n"
    "};\n"
    "if (typeof queueMicrotask !== 'function') W.queueMicrotask = function(f){ Promise.resolve().then(f); };\n"
    "if (!String.raw) String.raw = function(s){ var r = s.raw, out = ''; for (var i = 0; i < r.length; i++) { out += r[i]; if (i + 1 < arguments.length && i + 1 < r.length) out += arguments[i + 1]; } return out; };\n"
    "/* iterators over arrays and array-likes (for-of on arrays is native, but\n"
    " * code also calls a[Symbol.iterator]() / .values() / .entries() itself) */\n"
    "var mkIt = function(a, kind){ var i = 0; var it = { next: function(){\n"
    "    if (i >= a.length) return {value: undefined, done: true};\n"
    "    var k = i++; return {value: kind === 1 ? k : kind === 2 ? [k, a[k]] : a[k], done: false}; } };\n"
    "  it[Symbol.iterator] = function(){ return it; }; return it; };\n"
    "var AP = Array.prototype;\n"
    "if (!AP[Symbol.iterator]) AP[Symbol.iterator] = function(){ return mkIt(this, 0); };\n"
    "if (!AP.values) AP.values = function(){ return mkIt(this, 0); };\n"
    "if (!AP.keys) AP.keys = function(){ return mkIt(this, 1); };\n"
    "if (!AP.entries) AP.entries = function(){ return mkIt(this, 2); };\n"
    "/* typed arrays: the methods that take callbacks (the rest are native, script_typed.c) */\n"
    "var TP = W.__TypedArrayProto;\n"
    "if (TP) {\n"
    "  var mk = function(t, n){ return new t.constructor(n); };\n"
    "  TP.forEach = function(f, th){ for (var i = 0; i < this.length; i++) f.call(th, this[i], i, this); };\n"
    "  TP.map = function(f, th){ var r = mk(this, this.length); for (var i = 0; i < this.length; i++) r[i] = f.call(th, this[i], i, this); return r; };\n"
    "  TP.filter = function(f, th){ var a = []; for (var i = 0; i < this.length; i++) if (f.call(th, this[i], i, this)) a.push(this[i]); return new this.constructor(a); };\n"
    "  TP.reduce = function(f, acc){ var i = 0; if (arguments.length < 2) acc = this[i++]; for (; i < this.length; i++) acc = f(acc, this[i], i, this); return acc; };\n"
    "  TP.reduceRight = function(f, acc){ var i = this.length - 1; if (arguments.length < 2) acc = this[i--]; for (; i >= 0; i--) acc = f(acc, this[i], i, this); return acc; };\n"
    "  TP.every = function(f, th){ for (var i = 0; i < this.length; i++) if (!f.call(th, this[i], i, this)) return false; return true; };\n"
    "  TP.some = function(f, th){ for (var i = 0; i < this.length; i++) if (f.call(th, this[i], i, this)) return true; return false; };\n"
    "  TP.find = function(f, th){ for (var i = 0; i < this.length; i++) if (f.call(th, this[i], i, this)) return this[i]; };\n"
    "  TP.findIndex = function(f, th){ for (var i = 0; i < this.length; i++) if (f.call(th, this[i], i, this)) return i; return -1; };\n"
    "  TP.findLast = function(f, th){ for (var i = this.length - 1; i >= 0; i--) if (f.call(th, this[i], i, this)) return this[i]; };\n"
    "  TP.findLastIndex = function(f, th){ for (var i = this.length - 1; i >= 0; i--) if (f.call(th, this[i], i, this)) return i; return -1; };\n"
    "  TP.at = function(i){ i = Math.trunc(i) || 0; if (i < 0) i += this.length; return this[i]; };\n"
    "  TP.sort = function(f){ var a = []; for (var i = 0; i < this.length; i++) a.push(this[i]);\n"
    "    a.sort(f || function(x, y){ return x - y; }); for (var j = 0; j < a.length; j++) this[j] = a[j]; return this; };\n"
    "  TP.toString = function(){ return this.join(','); };\n"
    "  TP.toLocaleString = TP.toString;\n"
    "  TP.keys = function(){ return mkIt(this, 1); };\n"
    "  TP.values = function(){ return mkIt(this, 0); };\n"
    "  TP.entries = function(){ return mkIt(this, 2); };\n"
    "  TP[Symbol.iterator] = TP.values;\n"
    "}\n"
    "if (typeof TextEncoder === 'undefined') W.TextEncoder = class TextEncoder {\n"
    "  get encoding(){ return 'utf-8'; }\n"
    "  encode(s){ return __utf8_encode(s === undefined ? '' : String(s)); }\n"
    "  encodeInto(s, dst){ var b = __utf8_encode(String(s)), n = Math.min(b.length, dst.length); dst.set(b.subarray(0, n)); return {read: s.length, written: n}; }\n"
    "};\n"
    "if (typeof TextDecoder === 'undefined') W.TextDecoder = class TextDecoder {\n"
    "  constructor(l){ this.encoding = (l || 'utf-8').toLowerCase(); }\n"
    "  decode(b){ return b === undefined ? '' : __utf8_decode(b); }\n"
    "};\n"
    "if (typeof Reflect === 'undefined') W.Reflect = {\n"
    "  apply: function(f, t, a){ return f.apply(t, a || []); },\n"
    "  construct: function(C, a){ var A = a || []; switch (A.length) { case 0: return new C(); case 1: return new C(A[0]);\n"
    "    case 2: return new C(A[0], A[1]); case 3: return new C(A[0], A[1], A[2]); default: return new C(A[0], A[1], A[2], A[3]); } },\n"
    "  get: function(o, k){ return o[k]; },\n"
    "  set: function(o, k, v){ o[k] = v; return true; },\n"
    "  has: function(o, k){ return k in o; },\n"
    "  ownKeys: function(o){ return Object.getOwnPropertyNames(o); },\n"
    "  defineProperty: function(o, k, d){ try { Object.defineProperty(o, k, d); return true; } catch (e) { return false; } },\n"
    "  deleteProperty: function(o, k){ return delete o[k]; },\n"
    "  getPrototypeOf: function(o){ return Object.getPrototypeOf(o); },\n"
    "  setPrototypeOf: function(o, p){ Object.setPrototypeOf(o, p); return true; },\n"
    "  getOwnPropertyDescriptor: function(o, k){ return Object.getOwnPropertyDescriptor(o, k); },\n"
    "  isExtensible: function(){ return true; }, preventExtensions: function(){ return true; }\n"
    "};\n"
    "if (typeof escape !== 'function') {\n"
    "  W.escape = function(s){ s = String(s); var r = ''; for (var i = 0; i < s.length; i++) { var c = s.charCodeAt(i), ch = s.charAt(i);\n"
    "    if (/[A-Za-z0-9@*_+\\-.\\/]/.test(ch)) r += ch; else r += '%' + (c < 16 ? '0' : '') + c.toString(16).toUpperCase(); } return r; };\n"
    "  W.unescape = function(s){ return String(s).replace(/%([0-9A-Fa-f]{2})/g, function(m, h){ return String.fromCharCode(parseInt(h, 16)); }); };\n"
    "}\n"
    "var M = Math;\n"
    "if (!M.log1p) M.log1p = function(x){ return M.log(1 + x); };\n"
    "if (!M.expm1) M.expm1 = function(x){ return M.exp(x) - 1; };\n"
    "if (!M.sinh) M.sinh = function(x){ return (M.exp(x) - M.exp(-x)) / 2; };\n"
    "if (!M.cosh) M.cosh = function(x){ return (M.exp(x) + M.exp(-x)) / 2; };\n"
    "if (!M.tanh) M.tanh = function(x){ if (x > 20) return 1; if (x < -20) return -1; var a = M.exp(2 * x); return (a - 1) / (a + 1); };\n"
    "var O = Object, OP = Object.prototype;\n"
    "if (!O.isExtensible) O.isExtensible = function(){ return true; };\n"
    "if (!O.getOwnPropertySymbols) O.getOwnPropertySymbols = function(){ return []; };\n"
    "if (!O.getOwnPropertyDescriptors) O.getOwnPropertyDescriptors = function(o){ var r = {}; O.getOwnPropertyNames(o).forEach(function(k){ r[k] = O.getOwnPropertyDescriptor(o, k); }); return r; };\n"
    "if (!OP.isPrototypeOf) OP.isPrototypeOf = function(o){ while (o != null) { o = O.getPrototypeOf(o); if (o === this) return true; } return false; };\n"
    "if (!OP.propertyIsEnumerable) OP.propertyIsEnumerable = function(k){ return O.prototype.hasOwnProperty.call(this, k); };\n"
    "if (!OP.valueOf) OP.valueOf = function(){ return this; };\n"
    "if (!OP.toLocaleString) OP.toLocaleString = function(){ return this.toString(); };\n"
    "var NP = Number.prototype;\n"
    "if (!NP.toPrecision) NP.toPrecision = function(p){ if (p === undefined) return String(this); var x = Number(this);\n"
    "  if (x === 0) return x.toFixed(p - 1); var e = Math.floor(Math.log10(Math.abs(x))); return (e < -6 || e >= p) ? x.toExponential(p - 1) : x.toFixed(Math.max(0, p - 1 - e)); };\n"
    "if (!NP.toExponential) NP.toExponential = function(d){ var x = Number(this); if (x === 0) return (d ? (0).toFixed(d) : '0') + 'e+0';\n"
    "  var e = Math.floor(Math.log10(Math.abs(x))), m = x / Math.pow(10, e); if (d === undefined) d = Math.max(0, String(m).replace('-', '').length - 2);\n"
    "  var ms = m.toFixed(d); if (Math.abs(parseFloat(ms)) >= 10) { e++; ms = (m / 10).toFixed(d); } return ms + 'e' + (e < 0 ? '-' : '+') + Math.abs(e); };\n"
    "if (!NP.toLocaleString) NP.toLocaleString = function(){ var p = String(this).split('.'); p[0] = p[0].replace(/\\B(?=(\\d{3})+(?!\\d))/g, ','); return p.join('.'); };\n"
    "var SP = String.prototype;\n"
    "if (!SP.toLocaleLowerCase) SP.toLocaleLowerCase = SP.toLowerCase;\n"
    "if (!SP.toLocaleUpperCase) SP.toLocaleUpperCase = SP.toUpperCase;\n"
    "if (!Array.prototype.copyWithin) Array.prototype.copyWithin = function(t, s, e){ var n = this.length, c = this.slice(s, e === undefined ? n : e);\n"
    "  for (var i = 0; i < c.length && t + i < n; i++) this[t + i] = c[i]; return this; };\n"
    "if (!Function.prototype.toString) Function.prototype.toString = function(){ return 'function ' + (this.name || '') + '() { [native code] }'; };\n"
    "if (typeof WeakRef === 'undefined') W.WeakRef = class WeakRef { constructor(t){ this._t = t; } deref(){ return this._t; } };\n"
    "if (typeof Headers === 'undefined') W.Headers = class Headers {\n"
    "  constructor(i){ this._h = {}; if (i) { if (i._h) i = i._h; for (var k in i) this._h[k.toLowerCase()] = String(i[k]); } }\n"
    "  get(k){ var v = this._h[String(k).toLowerCase()]; return v === undefined ? null : v; }\n"
    "  set(k, v){ this._h[String(k).toLowerCase()] = String(v); } append(k, v){ var o = this.get(k); this.set(k, o === null ? v : o + ', ' + v); }\n"
    "  has(k){ return this.get(k) !== null; } delete(k){ delete this._h[String(k).toLowerCase()]; }\n"
    "  forEach(f, t){ for (var k in this._h) f.call(t, this._h[k], k, this); }\n"
    "  entries(){ var a = []; for (var k in this._h) a.push([k, this._h[k]]); return a[Symbol.iterator](); }\n"
    "  [Symbol.iterator](){ return this.entries(); }\n"
    "};\n"
    "if (typeof FormData === 'undefined') W.FormData = class FormData {\n"
    "  constructor(){ this._l = []; } append(k, v){ this._l.push([k, String(v)]); } set(k, v){ this.delete(k); this.append(k, v); }\n"
    "  get(k){ for (var p of this._l) if (p[0] === k) return p[1]; return null; } getAll(k){ return this._l.filter(function(p){ return p[0] === k; }).map(function(p){ return p[1]; }); }\n"
    "  has(k){ return this.get(k) !== null; } delete(k){ this._l = this._l.filter(function(p){ return p[0] !== k; }); }\n"
    "  entries(){ return this._l.slice()[Symbol.iterator](); } [Symbol.iterator](){ return this.entries(); }\n"
    "};\n"
    "if (typeof Blob === 'undefined') W.Blob = class Blob {\n"
    "  constructor(parts, o){ this._s = (parts || []).map(function(p){ return p && p.byteLength !== undefined && typeof p !== 'string' ? __utf8_decode(p) : String(p); }).join('');\n"
    "    this.type = (o && o.type) || ''; }\n"
    "  get size(){ return this._s.length; }\n"
    "  text(){ return Promise.resolve(this._s); }\n"
    "  arrayBuffer(){ return Promise.resolve(__utf8_encode(this._s).buffer); }\n"
    "  slice(a, b, t){ var r = new Blob([this._s.slice(a, b)]); r.type = t || ''; return r; }\n"
    "};\n"
    "if (W.crypto && crypto.getRandomValues) crypto.getRandomValues = function(a){ for (var i = 0; i < a.length; i++) a[i] = Math.floor(Math.random() * 4294967296); return a; };\n"
    "})();\n"
;
