/* generated from prelude.js by web/test/embed.pl: do not edit */
static const char k_prelude[] =
    "/* Run in every page before its own scripts: the web APIs that are easier to\n"
    " * write in script than in C.  web/prelude.h is generated from this file by\n"
    " * web/test/embed.pl. */\n"
    "(function(){\n"
    "var W = window, P = performance, marks = [];\n"
    "P.mark = function(n){ var e = {name:n, entryType:'mark', startTime:P.now(), duration:0}; marks.push(e); return e; };\n"
    "P.measure = function(n){ var e = {name:n, entryType:'measure', startTime:0, duration:P.now()}; marks.push(e); return e; };\n"
    "P.getEntriesByName = function(n){ return marks.filter(function(e){ return e.name === n; }); };\n"
    "P.getEntriesByType = function(t){ return marks.filter(function(e){ return e.entryType === t; }); };\n"
    "P.getEntries = function(){ return marks.slice(); };\n"
    "P.clearMarks = P.clearMeasures = function(){ marks = []; };\n"
    "P.timeOrigin = 0; P.timing = {navigationStart:0}; P.navigation = {type:0};\n"
    "function enc(s){ return encodeURIComponent(s).replace(/%20/g, '+'); }\n"
    "function dec(s){ try { return decodeURIComponent(s.replace(/\\+/g, ' ')); } catch (e) { return s; } }\n"
    "class URLSearchParams {\n"
    "  constructor(init){ this._l = []; if (init == null) return;\n"
    "    if (typeof init === 'object') {\n"
    "      if (Array.isArray(init)) { for (var p of init) this._l.push([String(p[0]), String(p[1])]); }\n"
    "      else if (init._l) { this._l = init._l.map(function(p){ return [p[0], p[1]]; }); }\n"
    "      else { for (var k in init) this._l.push([k, String(init[k])]); }\n"
    "      return; }\n"
    "    var s = String(init); if (s[0] === '?') s = s.slice(1);\n"
    "    for (var part of s.split('&')) { if (!part) continue; var i = part.indexOf('=');\n"
    "      this._l.push(i < 0 ? [dec(part), ''] : [dec(part.slice(0, i)), dec(part.slice(i + 1))]); } }\n"
    "  get(k){ for (var p of this._l) if (p[0] === k) return p[1]; return null; }\n"
    "  getAll(k){ return this._l.filter(function(p){ return p[0] === k; }).map(function(p){ return p[1]; }); }\n"
    "  has(k){ return this.get(k) !== null; }\n"
    "  set(k, v){ var done = false; this._l = this._l.filter(function(p){ if (p[0] !== k) return true; if (done) return false; p[1] = String(v); done = true; return true; });\n"
    "    if (!done) this._l.push([k, String(v)]); if (this._u) this._u._sync(); }\n"
    "  append(k, v){ this._l.push([k, String(v)]); if (this._u) this._u._sync(); }\n"
    "  delete(k){ this._l = this._l.filter(function(p){ return p[0] !== k; }); if (this._u) this._u._sync(); }\n"
    "  forEach(f, t){ for (var p of this._l) f.call(t, p[1], p[0], this); }\n"
    "  keys(){ return this._l.map(function(p){ return p[0]; })[Symbol.iterator](); }\n"
    "  values(){ return this._l.map(function(p){ return p[1]; })[Symbol.iterator](); }\n"
    "  entries(){ return this._l.map(function(p){ return [p[0], p[1]]; })[Symbol.iterator](); }\n"
    "  [Symbol.iterator](){ return this.entries(); }\n"
    "  get size(){ return this._l.length; }\n"
    "  sort(){ this._l.sort(function(a, b){ return a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0; }); }\n"
    "  toString(){ return this._l.map(function(p){ return enc(p[0]) + '=' + enc(p[1]); }).join('&'); }\n"
    "}\n"
    "function resolve(u, base){\n"
    "  if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(u)) return u;\n"
    "  if (base == null) throw new TypeError('Invalid URL: ' + u);\n"
    "  var b = new URL(String(base));\n"
    "  if (u.slice(0, 2) === '//') return b.protocol + u;\n"
    "  if (u[0] === '/') return b.origin + u;\n"
    "  if (u[0] === '?') return b.origin + b.pathname + u;\n"
    "  if (u[0] === '#') return b.origin + b.pathname + b.search + u;\n"
    "  if (u === '') return b.origin + b.pathname + b.search;\n"
    "  var dir = b.pathname.slice(0, b.pathname.lastIndexOf('/') + 1), segs = (dir + u).split('/'), out = [];\n"
    "  for (var i = 0; i < segs.length; i++) { var s = segs[i];\n"
    "    if (s === '..') { if (out.length > 1) out.pop(); if (i === segs.length - 1) out.push(''); }\n"
    "    else if (s === '.') { if (i === segs.length - 1) out.push(''); }\n"
    "    else out.push(s); }\n"
    "  return b.origin + out.join('/');\n"
    "}\n"
    "var URL_RX = /^([a-zA-Z][a-zA-Z0-9+.-]*:)(?:\\/\\/(?:([^:@\\/]*)(?::([^@\\/]*))?@)?([^:\\/?#]*)(?::(\\d+))?)?([^?#]*)(\\?[^#]*)?(#.*)?$/;\n"
    "class URL {\n"
    "  constructor(u, base){ this._set(resolve(String(u), base)); }\n"
    "  _set(s){\n"
    "    var m = URL_RX.exec(s);\n"
    "    if (!m) throw new TypeError('Invalid URL: ' + s);\n"
    "    this.protocol = m[1].toLowerCase(); this.username = m[2] || ''; this.password = m[3] || '';\n"
    "    this.hostname = (m[4] || '').toLowerCase(); this.port = m[5] || '';\n"
    "    this.pathname = m[6] || (m[4] != null ? '/' : '');\n"
    "    this.search = m[7] && m[7] !== '?' ? m[7] : ''; this.hash = m[8] && m[8] !== '#' ? m[8] : '';\n"
    "    this.searchParams = new URLSearchParams(this.search); this.searchParams._u = this;\n"
    "  }\n"
    "  _sync(){ var q = this.searchParams.toString(); this.search = q ? '?' + q : ''; }\n"
    "  get host(){ return this.hostname + (this.port ? ':' + this.port : ''); }\n"
    "  get origin(){ return this.protocol + '//' + this.host; }\n"
    "  get href(){ return this.origin + this.pathname + this.search + this.hash; }\n"
    "  set href(v){ this._set(String(v)); }\n"
    "  toString(){ return this.href; }\n"
    "  toJSON(){ return this.href; }\n"
    "  static canParse(u, b){ try { new URL(u, b); return true; } catch (e) { return false; } }\n"
    "  static createObjectURL(){ return 'blob:null'; }\n"
    "  static revokeObjectURL(){}\n"
    "}\n"
    "W.URL = URL; W.URLSearchParams = URLSearchParams;\n"
    "\n"
    "/* event targets that are not elements (signals, ports, `class X extends EventTarget`) */\n"
    "class EventTarget {\n"
    "  addEventListener(t, f, o){ if (!f) return; var l = this.__ls || (this.__ls = {});\n"
    "    (l[t] || (l[t] = [])).push({f: f, once: !!(o && typeof o === 'object' && o.once)}); }\n"
    "  removeEventListener(t, f){ var l = this.__ls && this.__ls[t]; if (l) this.__ls[t] = l.filter(function(x){ return x.f !== f; }); }\n"
    "  dispatchEvent(ev){\n"
    "    try { if (!ev.target) ev.target = this; ev.currentTarget = this; } catch (e) {}\n"
    "    var h = this['on' + ev.type]; if (typeof h === 'function') h.call(this, ev);\n"
    "    var l = this.__ls && this.__ls[ev.type];\n"
    "    if (l) for (var x of l.slice()) {\n"
    "      if (x.once) this.removeEventListener(ev.type, x.f);\n"
    "      if (typeof x.f === 'function') x.f.call(this, ev); else if (x.f && x.f.handleEvent) x.f.handleEvent(ev);\n"
    "    }\n"
    "    return !ev.defaultPrevented;\n"
    "  }\n"
    "}\n"
    "class AbortSignal extends EventTarget {\n"
    "  constructor(){ super(); this.aborted = false; this.reason = undefined; this.onabort = null; }\n"
    "  throwIfAborted(){ if (this.aborted) throw this.reason; }\n"
    "  static abort(r){ var c = new AbortController(); c.abort(r); return c.signal; }\n"
    "  static timeout(ms){ var c = new AbortController(); setTimeout(function(){ c.abort(new Error('TimeoutError')); }, ms); return c.signal; }\n"
    "  static any(list){ var c = new AbortController();\n"
    "    for (var s of list) { if (s.aborted) { c.abort(s.reason); break; } s.addEventListener('abort', function(){ c.abort(this.reason); }); }\n"
    "    return c.signal; }\n"
    "}\n"
    "class AbortController {\n"
    "  constructor(){ this.signal = new AbortSignal(); }\n"
    "  abort(r){ var s = this.signal; if (s.aborted) return; s.aborted = true;\n"
    "    s.reason = r === undefined ? new Error('AbortError') : r; s.dispatchEvent({type: 'abort', target: s}); }\n"
    "}\n"
    "/* MessageChannel: messages arrive on the next turn (React's scheduler uses it) */\n"
    "class MessagePort extends EventTarget {\n"
    "  constructor(){ super(); this.onmessage = null; this._other = null; }\n"
    "  postMessage(d){ var o = this._other; setTimeout(function(){ o.dispatchEvent({type: 'message', data: d}); }, 0); }\n"
    "  start(){} close(){}\n"
    "}\n"
    "class MessageChannel {\n"
    "  constructor(){ this.port1 = new MessagePort(); this.port2 = new MessagePort(); this.port1._other = this.port2; this.port2._other = this.port1; }\n"
    "}\n"
    "W.EventTarget = EventTarget; W.AbortSignal = AbortSignal; W.AbortController = AbortController;\n"
    "W.MessagePort = MessagePort; W.MessageChannel = MessageChannel;\n"
    "var EP = Element.prototype;\n"
    "if (!EP.getRootNode) EP.getRootNode = function(){ var n = this; while (n.parentNode) n = n.parentNode; return n; };\n"
    "if (typeof crypto === 'undefined') W.crypto = {\n"
    "  getRandomValues: function(a){ for (var i = 0; i < a.length; i++) a[i] = Math.floor(Math.random() * 256); return a; },\n"
    "  randomUUID: function(){ return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c){\n"
    "    var r = Math.floor(Math.random() * 16); return (c === 'x' ? r : (r & 3) | 8).toString(16); }); },\n"
    "  subtle: {}\n"
    "};\n"
    "var D = document;\n"
    "if (!D.styleSheets) D.styleSheets = [];\n"
    "if (!D.adoptedStyleSheets) D.adoptedStyleSheets = [];\n"
    "if (!D.fonts) D.fonts = { ready: Promise.resolve(), status: 'loaded', check: function(){ return true; },\n"
    "  load: function(){ return Promise.resolve([]); }, add: function(){}, delete: function(){}, forEach: function(){},\n"
    "  addEventListener: function(){}, removeEventListener: function(){} };\n"
    "if (typeof CSSStyleSheet === 'undefined') W.CSSStyleSheet = class CSSStyleSheet {\n"
    "  constructor(){ this.cssRules = []; } replaceSync(t){ this.text = t; } replace(t){ this.text = t; return Promise.resolve(this); }\n"
    "  insertRule(r, i){ this.cssRules.splice(i || 0, 0, {cssText: r}); return i || 0; } deleteRule(i){ this.cssRules.splice(i, 1); }\n"
    "};\n"
    "if (typeof queueMicrotask !== 'function') W.queueMicrotask = function(f){ Promise.resolve().then(f); };\n"
    "if (!String.raw) String.raw = function(s){ var r = s.raw, out = ''; for (var i = 0; i < r.length; i++) { out += r[i]; if (i + 1 < arguments.length && i + 1 < r.length) out += arguments[i + 1]; } return out; };\n"
    "})();\n"
;
